### ISSUE TITLE
Release mirrored to local registry may not match the one in install-config

### ISSUE THREAD

**Issue by cybertron** [openshift-metal3/dev-scripts#1001]
Because by default OPENSHIFT_RELEASE_IMAGE is re-set in every script[0], it is possible that the release used by the mirror command[1] may not match the release that is later written to install-config ([2], which eventually calls [3]) if a new latest release image is published in between. This results in mirroring not working correctly, which means we either pull images remotely when we shouldn't or just fail completely in cases such as an ipv6 deployment where the upstream registry is ipv4-only. We need to make sure that the same release image is used for mirroring and install.

0: https://github.com/openshift-metal3/dev-scripts/blob/142758dc97a8663203e88414ac12ee612a839dac/common.sh#L113
1: https://github.com/openshift-metal3/dev-scripts/blob/master/04_setup_ironic.sh#L71
2: https://github.com/openshift-metal3/dev-scripts/blob/142758dc97a8663203e88414ac12ee612a839dac/06_create_cluster.sh#L58
3: https://github.com/openshift-metal3/dev-scripts/blob/142758dc97a8663203e88414ac12ee612a839dac/utils.sh#L241

**Comment by stbenjam** [comment]
Ah good find. It's a long-standing issue that we recalculate values every time, it was only a matter of time before someone ran into something like this. 

One idea to fix this could be that we write out static values for the things in common.sh to a file and then source that.

**Comment by cybertron** [comment]
I pushed a PR for the mirror problem specifically, but that doesn't handle anything else right now. One option would be to dump out all of the common.sh values in the 01 script and then reuse them after that, but then if someone skips the 01 script because they've already installed requirements they won't have the file. I don't know if we care about being able to run the scripts piecemeal like that or if we're okay saying that you need to run all of them in order.

We could also just write the file if it doesn't exist and use it if it does, but then if a file gets left from a previous deploy somehow you might get stale values. I suppose we could just delete the file first thing in the 01 script. That would have the same problem if someone skipped it, but the file being left around should be much less common.

**Comment by dhellmann** [comment]
We could add a `00` step to generate the variables and have the other steps only load the generated file. That way we retain the ability to run some of the current steps independently.

**Comment by dhellmann** [comment]
At some point we're re-inventing the state management that an ansible playbook gives us, too, so we could think seriously about what converting to another tool might look like. :-)
