### ISSUE TITLE
RFE -- Simplify the deployment of specific nightly, CI, and GA builds

### ISSUE THREAD

**Issue by dustinblack** [openshift-metal3/dev-scripts#1038]
**Describe the bug**
I am specifically trying to run a dev-scripts install of a specific GA release. To do this, I have to first know to navigate to https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.4.4/release.txt and take the `Pull From` value to place into the `OPENSHIFT_RELEASE_IMAGE` var, and then also set `OPENSHIFT_CI=true`, none of which is intuitive.

**Expected/observed behavior**
It would be nice to have vars something like the below to indicate a build explicitly by it's name on the mirror, and allow the scripts to parse this to select the other required values.

`OPENSHIFT_BUILD="ga"`
`OPENSHIFT_VERSION="4.4.4"`

This is based on the method used in the ansible-ipi deployment automation.
https://github.com/openshift-kni/baremetal-deploy/blob/708b53eae85c842814798a0c2fda35ba31ccb5ec/ansible-ipi-install/inventory/hosts.sample#L27

**Comment by hardys** [comment]
Thanks for this - I agree we should make this easier, can you clarify why you needed `OPENSHIFT_CI=true`?  I guess you installed the `oc` binary manually?

I think the majority of folks are testing either CI builds (the default) or CI nightlies, but it would be good to add an easy way to also test GA builds as well.

**Comment by dustinblack** [comment]
> Thanks for this - I agree we should make this easier, can you clarify why you needed `OPENSHIFT_CI=true`? I guess you installed the `oc` binary manually?

I actually applied that per someone's recommendation, so I'm not sure its effect or why it might be necessary.

**Comment by hardys** [comment]
https://github.com/openshift-metal3/dev-scripts/pull/1052 landed which makes it easier to test specific branches of CI build based on the version, we could perhaps add to that the ability to specify CI/nightly, then look at how to consume downstream builds.
