### ISSUE TITLE
[Doc] CI builds does not work with pull secret from https://cloud.redhat.com/openshift/install/pull-secret

### ISSUE THREAD

**Issue by FilipB** [openshift-metal3/dev-scripts#1065]
**Describe the bug**
https://github.com/openshift-metal3/dev-scripts#pre-requisites say to get a valid pull secret (json string) from https://cloud.redhat.com/openshift/install/pull-secret but that secret does not work with builds from https://openshift-release.svc.ci.openshift.org which are used by default.

**To Reproduce**
Follow Pre-requisites and paste pull secrets to ```config_$USER.sh``` and run ```make```

**Expected/observed behavior**
Installation fails because the pull secret from https://cloud.redhat.com/openshift/install/pull-secret is not valid for builds from registry.svc.ci.openshift.org

It's necessary to add pull secret for registry.svc.ci.openshift.org to make that work.

**Comment by markmc** [comment]
Thanks, this should be resolved with #1093 - you now put your pull secret in `pull_secret.json` and a token for the CI cluster in `config_$USER.sh`.
