### ISSUE TITLE
Pull request #1071 added some strange buffering

### ISSUE THREAD

**Issue by bcrochet** [openshift-metal3/dev-scripts#1121]
**Describe the bug**
https://github.com/openshift-metal3/dev-scripts/pull/1071 added some buffering to the terminal.

**To Reproduce**
Run dev-scripts on terminal. Watch it pause.

**Expected/observed behavior**
No buffering as before.

**Additional context**
Reverting #1071 returns the terminal to it's previous glory.

**Comment by zaneb** [comment]
If the output of awk is not to a tty, then it will not be line buffered. It appears the only way to [fix this in awk](https://www.gnu.org/software/gawk/manual/html_node/I_002fO-Functions.html) is to call `fflush()` after each output.
