### ISSUE TITLE
Allow creating a custom number of extra disks

### ISSUE THREAD

**Issue by flaper87** [openshift-metal3/dev-scripts#1228]
dev-scripts allows for creating an extra disks with `VM_EXTRADISKS` but it's hardcoded to 1 disk of 8GB. For cases like Assisted deployment https://github.com/openshift-metal3/dev-scripts/pull/1223 it would be useful to be able to specify the following:

- Number of disks
- Size
- device name (? Unsure about this one)

**Comment by hardys** [comment]
@flaper87 I think we can close this since https://github.com/openshift-metal3/dev-scripts/pull/1246 landed?

**Comment by flaper87** [comment]
Yup, thanks!
