### ISSUE TITLE
Align Ansible version to metal3-dev-env one

### ISSUE THREAD

**Issue by andfasano** [openshift-metal3/dev-scripts#1276]
Currently dev-scripts works fine with Ansible 2.9. The master branch of metal3-dev-env anyhow is currently using a newer Ansible version (4.0.0) which is not fully backward compatible, thus making very difficult using both of them on the same machine.
It could be then useful to have the same version so that both repo could be use don the same machine without any issue.

(note: right now, after having executed metal3-dev-env, it is necessary to uninstall _both_ `ansible` and `ansible-core` to let dev-scritps work again)

**Comment by hardys** [comment]
I think this was fixed via https://github.com/openshift-metal3/dev-scripts/pull/1301 - we'll still need to bump the metal3-dev-env pin (and ANSIBLE_VERSION) periodically, but it should now be easier to keep things in sync

**Comment by andfasano** [comment]
Thanks @hardys
