### ISSUE TITLE
make failed with "deploy/crds/kubevirt_v1alpha1_kwebui_cr.yaml"

### ISSUE THREAD

**Issue by AsherShoshan** [openshift-metal3/dev-scripts#376]
Creating a new cluster failes with the above (even after delete and clone dev-script repo)

+ git checkout master
Already on 'master'
M	deploy/crds/kubevirt_v1alpha1_kwebui_cr.yaml
+ git pull --rebase origin master
Cannot pull with rebase: You have unstaged changes.
Please commit or stash them.
make: *** [repo_sync] Error 1

**Comment by hardys** [comment]
This is a regression caused by https://github.com/openshift-metalkube/dev-scripts/pull/216 - we need to avoid sedding in-place similar to https://github.com/openshift-metalkube/dev-scripts/pull/316

cc @karmab

**Comment by russellb** [comment]
Looks like this was fixed already
