### ISSUE TITLE
make clean doesn't remove the vbmc configurations and daemons 

### ISSUE THREAD

**Issue by gklein** [openshift-metal3/dev-scripts#378]
After running "make clean" vbmcd is still running and vm configuration files are still in place

*# vbmc list*
+--------------------+---------+---------+------+
| Domain name        | Status  | Address | Port |
+--------------------+---------+---------+------+
| openshift_master_0 | running | ::      | 6230 |
| openshift_master_1 | running | ::      | 6231 |
| openshift_master_2 | running | ::      | 6232 |
| openshift_worker_0 | running | ::      | 6233 |
| openshift_worker_1 | running | ::      | 6234 |
| openshift_worker_2 | running | ::      | 6235 |
+--------------------+---------+---------+------+

*# ps aux|grep vbmc*
root      6477  0.1  0.0 486140 26124 ?        Ssl  Apr11  12:39 /usr/bin/python2 /usr/bin/vbmcd --foreground
root      6844  0.1  0.0 538748 35224 ?        Sl   Apr11  10:55 /usr/bin/python2 /usr/bin/vbmcd --foreground
root      6890  0.1  0.0 538892 35884 ?        Sl   Apr11  11:00 /usr/bin/python2 /usr/bin/vbmcd --foreground
root      6933  0.1  0.0 538892 36228 ?        Sl   Apr11  10:59 /usr/bin/python2 /usr/bin/vbmcd --foreground
root      6979  0.0  0.0 485752  5924 ?        Sl   Apr11   7:40 /usr/bin/python2 /usr/bin/vbmcd --foreground
root      7023  0.0  0.0 485752  5916 ?        Sl   Apr11   7:44 /usr/bin/python2 /usr/bin/vbmcd --foreground
root      7066  0.0  0.0 485752  5936 ?        Sl   Apr11   7:39 /usr/bin/python2 /usr/bin/vbmcd --foreground

*# ls -l /root/.vbmc/*
total 4
-rw-------. 1 root root  4 Apr 11 10:48 master.pid
drwxr-xr-x. 2 root root 20 Apr 11 10:48 openshift_master_0
drwxr-xr-x. 2 root root 20 Apr 11 10:48 openshift_master_1
drwxr-xr-x. 2 root root 20 Apr 11 10:48 openshift_master_2
drwxr-xr-x. 2 root root 20 Apr 11 10:48 openshift_worker_0
drwxr-xr-x. 2 root root 20 Apr 11 10:48 openshift_worker_1
drwxr-xr-x. 2 root root 20 Apr 11 10:48 openshift_worker_2

**Comment by hardys** [comment]
Thanks, I noticed the same yesterday and AFAICS teardown of the virtbmc stuff is missing from openstack/tripleo-quickstart where we copied the ansible roles from.

So perhaps we may want to push a fix there too in due course.
