### ISSUE TITLE
`worker-0` is hardcoded

### ISSUE THREAD

**Issue by e-minguez** [openshift-metal3/dev-scripts#417]
**Describe the bug**
When deploying workers with names different than `worker-0` the register script will never finish.

**To Reproduce**
Run a deployment with workers such as:

```
{
  "name": "kni1-worker-0",
  "driver": "ipmi",                                                                                                                               
...
```                                                             

**Expected/observed behavior**
The wait should be done for the node name instead

**Additional context**
https://github.com/openshift-metalkube/dev-scripts/blob/master/11_register_hosts.sh#L95

**Comment by russellb** [comment]
OK - I think we should just skip this part if it's a baremetal deployment.  This was just an additional easy step to automate in the virt case where we can make more assumptions about what's configured.

**Comment by e-minguez** [comment]
Closing this via #433
I'm assuming the procedure to add workers will be to use the following procedure https://github.com/metal3-io/baremetal-operator/blob/master/docs/dev-setup.md#using-bare-metal-hosts

**Comment by russellb** [comment]
Yes, create `BareMetalHosts` for your workers, and then scale up the worker `MachineSet`
