### ISSUE TITLE
Deleting baremetalhost added with wrong ipmi details fails.

### ISSUE THREAD

**Issue by achuzhoy** [openshift-metal3/dev-scripts#419]
Deleting baremetalhost added with wrong ipmi details fails.

Environment:
[stack@rhos-compute-node-14 dev-scripts]$ oc get clusterversion
NAME      VERSION                        AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.0.0-0.ci-2019-04-17-133604   True        False         3d10h   Cluster version is 4.0.0-0.ci-2019-04-17-133604

Steps to reproduce:

Attempt to add a baremetalhost with wrong ipmi details. Its "PROVISIONING STATUS" with be stuck with "registering":

[stack@rhos-compute-node-14 dev-scripts]$ oc get -n openshift-machine-api baremetalhost
NAME            STATUS   PROVISIONING STATUS   MACHINE           BMC                         HARDWARE PROFILE   ONLINE   ERROR
sasha-worker    OK       registering           ostest-master-0   ipmi://192.168.122.6:6233                      true  

Attempt to delete it with "oc delete -n openshift-machine-api baremetalhost/sasha-worker"

Result:
The baremetalhost isn't deleted. 
The logs show:

{"level":"info","ts":1556032276.328309,"logger":"baremetalhost","msg":"Reconciling BareMetalHost","Request.Namespace":"openshift-machine-api","Request.Name":"sasha-worker"}
{"level":"info","ts":1556032276.328395,"logger":"baremetalhost","msg":"marked to be deleted","Request.Namespace":"openshift-machine-api","Request.Name":"sasha-worker","timestamp":"2019-04-23 15:11:16 +0000 UTC"}
{"level":"info","ts":1556032276.328459,"logger":"baremetalhost","msg":"updating owner of secret","Request.Namespace":"openshift-machine-api","Request.Name":"sasha-worker"}
{"level":"info","ts":1556032276.3285193,"logger":"baremetalhost","msg":"deprovisioning","Request.Namespace":"openshift-machine-api","Request.Name":"sasha-worker"}
{"level":"info","ts":1556032276.3285341,"logger":"baremetalhost_ironic","msg":"deprovisioning","host":"sasha-worker"}
{"level":"info","ts":1556032276.356097,"logger":"baremetalhost_ironic","msg":"found existing node by ID","host":"sasha-worker"}
{"level":"info","ts":1556032276.356144,"logger":"baremetalhost_ironic","msg":"deprovisioning host","host":"sasha-worker","ID":"dad7f1a3-0810-4fbe-9010-c26eeaecf510","lastError":"Failed to get power state for node dad7f1a3-0810-4fbe-9010-c26eeaecf510. Error: IPMI call failed: power status.","current":"enroll","target":"","deploy step":{}}
{"level":"info","ts":1556032276.356191,"logger":"baremetalhost_ironic","msg":"starting delete","host":"sasha-worker"}
{"level":"info","ts":1556032276.3562262,"logger":"baremetalhost","msg":"publishing event","reason":"DeprovisioningStarted","message":"Image deprovisioning started"}
{"level":"info","ts":1556032276.3955088,"logger":"baremetalhost_ironic","msg":"changing provisioning state","host":"sasha-worker","current":"enroll","existing target":"","new target":"deleted"}
{"level":"error","ts":1556032276.4196804,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"metalkube-baremetalhost-controller","request":"openshift-machine-api/sasha-worker","error":"failed to deprovision: failed to change provisioning state to \"deleted\": Bad request with: [PUT http://localhost:6385/v1/nodes/dad7f1a3-0810-4fbe-9010-c26eeaecf510/states/provision], error message: {\"error_message\": \"{\\\"debuginfo\\\": null, \\\"faultcode\\\": \\\"Client\\\", \\\"faultstring\\\": \\\"The requested action \\\\\\\"deleted\\\\\\\" can not be performed on node \\\\\\\"dad7f1a3-0810-4fbe-9010-c26eeaecf510\\\\\\\" while it is in state \\\\\\\"enroll\\\\\\\".\\\"}\"}","errorVerbose":"Bad request with: [PUT http://localhost:6385/v1/nodes/dad7f1a3-0810-4fbe-9010-c26eeaecf510/states/provision], error message: {\"error_message\": \"{\\\"debuginfo\\\": null, \\\"faultcode\\\": \\\"Client\\\", \\\"faultstring\\\": \\\"The requested action \\\\\\\"deleted\\\\\\\" can not be performed on node \\\\\\\"dad7f1a3-0810-4fbe-9010-c26eeaecf510\\\\\\\" while it is in state \\\\\\\"enroll\\\\\\\".\\\"}\"}\nfailed to change provisioning state to \"deleted\"\ngithub.com/metalkube/baremetal-operator/pkg/provisioner/ironic.(*ironicProvisioner).changeNodeProvisionState\n\t/go/src/github.com/metalkube/baremetal-operator/pkg/provisioner/ironic/ironic.go:334\ngithub.com/metalkube/baremetal-operator/pkg/provisioner/ironic.(*ironicProvisioner).Deprovision\n\t/go/src/github.com/metalkube/baremetal-operator/pkg/provisioner/ironic/ironic.go:910\ngithub.com/metalkube/baremetal-operator/pkg/controller/baremetalhost.(*ReconcileBareMetalHost).deleteHost\n\t/go/src/github.com/metalkube/baremetal-operator/pkg/controller/baremetalhost/baremetalhost_controller.go:394\ngithub.com/metalkube/baremetal-operator/pkg/controller/baremetalhost.(*ReconcileBareMetalHost).Reconcile\n\t/go/src/github.com/metalkube/baremetal-operator/pkg/controller/baremetalhost/baremetalhost_controller.go:199\ngithub.com/metalkube/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/metalkube/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:213\ngithub.com/metalkube/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/metalkube/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/metalkube/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/metalkube/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/metalkube/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/metalkube/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/metalkube/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/metalkube/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:2361\nfailed to deprovision\ngithub.com/metalkube/baremetal-operator/pkg/controller/baremetalhost.(*ReconcileBareMetalHost).deleteHost\n\t/go/src/github.com/metalkube/baremetal-operator/pkg/controller/baremetalhost/baremetalhost_controller.go:396\ngithub.com/metalkube/baremetal-operator/pkg/controller/baremetalhost.(*ReconcileBareMetalHost).Reconcile\n\t/go/src/github.com/metalkube/baremetal-operator/pkg/controller/baremetalhost/baremetalhost_controller.go:199\ngithub.com/metalkube/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/metalkube/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:213\ngithub.com/metalkube/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/metalkube/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/metalkube/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/metalkube/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/metalkube/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/metalkube/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/metalkube/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/metalkube/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:2361","stacktrace":"github.com/metalkube/baremetal-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/metalkube/baremetal-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/metalkube/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/metalkube/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/metalkube/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/metalkube/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/metalkube/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/metalkube/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/metalkube/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/metalkube/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/metalkube/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/metalkube/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}

[stack@rhos-compute-node-14 dev-scripts]$ openstack baremetal node list
+--------------------------------------+--------------------+--------------------------------------+-------------+--------------------+-------------+
| UUID                                 | Name               | Instance UUID                        | Power State | Provisioning State | Maintenance |
+--------------------------------------+--------------------+--------------------------------------+-------------+--------------------+-------------+
| f550d9d7-ce1a-4fc5-b6a1-aa96c09a2afc | openshift-master-2 | None                                 | power on    | active             | False       |
| 1747616b-2d9b-4ba5-8e76-2778721784c1 | openshift-master-1 | None                                 | power on    | active             | False       |
| 3564fb64-b480-4a6d-8dbb-c3bf948a88ab | openshift-master-0 | None                                 | power on    | active             | False       |
| dad7f1a3-0810-4fbe-9010-c26eeaecf510 | sasha-worker       | None                                 | None        | enroll             | False       |

W/A:

First delete the node in ironic:
openstack baremetal node delete sasha-worker

Then the deletion would work as expected and running "oc delete -n openshift-machine-api baremetalhost/sasha-worker" returns the prompt immediately and that baremetalhost is gone.

The issue is reported in BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1702373

**Comment by hardys** [comment]
I don't think this is a bug in dev-scripts, probably it should be raised against https://github.com/metal3-io/baremetal-operator ?

**Comment by hardys** [comment]
I tested locally and can confirm the issue, raised https://github.com/metal3-io/baremetal-operator/issues/170 to track fixing it

**Comment by hardys** [comment]
https://github.com/metal3-io/baremetal-operator/pull/171 pushed which aims to fix this, I'll close this issue and we can track resolution via metal3-io/baremetal-operator#170
