### ISSUE TITLE
Deploying dev-scripts on BM setup:  lots of failures due to timeout Waiting for ironic to respond

### ISSUE THREAD

**Issue by achuzhoy** [openshift-metal3/dev-scripts#442]
Deploying dev-scripts on BM setup:  lots of failures due to timeout Waiting for ironic to respond

Environment:
Last commit in https://github.com/metalkube/dev-scripts.git is: 34e4c9e319ba5fa81ca81d8a2e6152ecb460abe8

Under dev-scripts in 06_create_cluster.sh we have:

wait_for_json ironic \
    "${OS_URL}/v1/nodes" \
    20 \
    -H "Accept: application/json" -H "Content-Type: application/json" -H "User-Agent: wait-for-json" -H "X-Auth-Token: $OS_TOKEN"

if [ $(sudo podman ps | grep -w -e "ironic$" -e "ironic-inspector$" -e "dnsmasq" -e "httpd" | wc -l) != 4 ]; then
    echo "Can't find required containers"
    exit 1
fi

Lot's of failures during deployment are related to that:
15:36:06 + wait_for_json ironic http://localhost:6385//v1/nodes 20 -H 'Accept: application/json' -H 'Content-Type: application/json' -H 'User-Agent: wait-for-json' -H 'X-Auth-Token: fake-token'
15:36:06 + local name
15:36:06 + local url
15:36:06 + local curl_opts
15:36:06 + local timeout
15:36:06 + local start_time
15:36:06 + local curr_time
15:36:06 + local time_diff
15:36:06 + name=ironic
15:36:06 + url=http://localhost:6385//v1/nodes
15:36:06 + timeout=20
15:36:06 + shift 3
15:36:06 + curl_opts='-H Accept: application/json -H Content-Type: application/json -H User-Agent: wait-for-json -H X-Auth-Token: fake-token'
15:36:06 + echo -n 'Waiting for ironic to respond'
15:36:06 Waiting for ironic to respond++ date +%s
15:36:06 + start_time=1556120166
15:36:06 ++  curl -g j-Xq GET http://localhost:6385//v1/nodes  '-H Accept: application/json -H Content-Type: application/json -H User-Agent: wait-for-json -H X-Auth-Token: fake-token'.
15:36:06 
15:36:06 + echo -n .
15:36:06 .++ date +%s
15:36:06 + curr_time=1556120166
15:36:06 + time_diff=0
15:36:06 + [[ 0 -gt 20 ]]
15:36:06 + sleep 5
15:36:11 + curl -g -X GET http://localhost:6385//v1/nodes '-H Accept: application/json -H Content-Type: application/json -H User-Agent: wait-for-json -H X-Auth-Token: fake-token'
15:36:11 + jq .
15:36:11 + echo -n .
15:36:11 .++ date +%s
15:36:11 + curr_time=1556120171
15:36:11 + time_diff=5
15:36:11 + [[ 5 -gt 20 ]]
15:36:11 + sleep 5
15:36:16 + curl -g -X GET +http://localhost:6385//v1/nodes  '-H Accept: application/json -H Content-Type: application/json -H User-Agent: wait-for-json -H X-Auth-Token: fake-token'
15:36:16 jq .
15:36:16 + echo -n .
15:36:16 .++ date +%s
15:36:16 + curr_time=1556120176
15:36:16 + time_diff=10
15:36:16 + [[ 10 -gt 20 ]]
15:36:16 + sleep 5
15:36:21 + + jqcurl . -g -X
15:36:21  GET http://localhost:6385//v1/nodes '-H Accept: application/json -H Content-Type: application/json -H User-Agent: wait-for-json -H X-Auth-Token: fake-token'
15:36:21 + echo -n .
15:36:21 .++ date +%s
15:36:21 + curr_time=1556120181
15:36:21 + time_diff=15
15:36:21 + [[ 15 -gt 20 ]]
15:36:21 + sleep 5
15:36:26 ++  curljq -g -X  .GET http://localhost:6385//v1/nodes
15:36:26  '-H Accept: application/json -H Content-Type: application/json -H User-Agent: wait-for-json -H X-Auth-Token: fake-token'
15:36:26 + echo -n .
15:36:26 .++ date +%s
15:36:26 + curr_time=1556120186
15:36:26 + time_diff=20
15:36:26 + [[ 20 -gt 20 ]]
15:36:26 + sleep 5
15:36:31 + curl -g+ -X  GET http://localhost:6385//v1/nodes '-H Accept: application/json -H Content-Type: application/json -H User-Agent: wait-for-json -H X-Auth-Token: fake-token'
15:36:31 jq .
15:36:31 + echo -n .
15:36:31 .++ date +%s
15:36:31 + curr_time=1556120191
15:36:31 + time_diff=25
15:36:31 + [[ 25 -gt 20 ]]
15:36:31 + echo '\nTimed out waiting for ironic'
15:36:31 \nTimed out waiting for ironic
15:36:31 + return 1
15:36:31 make: *** [ocp_run] Error 1
15:36:31 Error! Exiting...
15:36:31 Build step 'Execute shell' marked build as failure
15:36:31 Finished: FAILURE

The issue is intermittent but happens very often.

Reported BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1702741

**Comment by russellb** [comment]
Does this still happen?

**Comment by hardys** [comment]
I'm going to close this as stale, please reopen if you're still seeing these issues.
