### ISSUE TITLE
Error pulling image ref //quay.io/metalkube/metalkube-ironic-inspector:latest

### ISSUE THREAD

**Issue by chunfuwen** [openshift-metal3/dev-scripts#473]
+ for IMAGE_VAR in IRONIC_IMAGE IRONIC_INSPECTOR_IMAGE
+ IMAGE=quay.io/metalkube/metalkube-ironic-inspector
+ [[ quay.io/metalkube/metalkube-ironic-inspector =~ :// ]]
+ sudo podman pull quay.io/metalkube/metalkube-ironic-inspector
Trying to pull docker://quay.io/metalkube/metalkube-ironic-inspector...Getting image source signatures
Copying blob sha256:8ba884070f611d31cb2c42eddb691319dc9facf5e0ec67672fcfa135181ab3df
Copying blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Copying blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Copying blob sha256:e1cf76388460811777c8d3e50c6876c86ffb0e2b15fabf954f9e45741e682940
Copying blob sha256:fb82da6e383cae47bd94236fb1c4c9cd595289c9fe1968644116fdd4df98d808
Copying blob sha256:0783fde546a99c19b2756c5b58acc040f6bff21c80715b30d31ce4b455855c0c
Copying blob sha256:6470073a2500c79f0fd68952146e941bd110e237ad461c77ac3fcdbb33b98889
Copying blob sha256:73e34fa7ce27064668b99dbf446267447126ecc51b786fa21600a7df30f7b833
Copying blob sha256:3c19661cc153e75c5bf17585af10047e892031f98c9702b8eda4d31bc1f60e86
Copying blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Copying blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Copying blob sha256:3e9e823f4e23c32650074ca601956c2c893598e90a7f88885fd44a74fc4163b9
Copying blob sha256:2f6585cfc6a8f7dc9cc001f4679b1f53b6aa35a1cf7e01f9c48db036ce3661a2
time="2019-04-27T22:33:09-04:00" level=error msg="Error pulling image ref //quay.io/metalkube/metalkube-ironic-inspector:latest: Error reading blob sha256:5d698ddfa421325b761d3a32014485ae44d73f9981af3243fed8b4ce0ab7f121: Get https://quay.io/v2/metalkube/metalkube-ironic-inspector/blobs/sha256:5d698ddfa421325b761d3a32014485ae44d73f9981af3243fed8b4ce0ab7f121: EOF" 
Failed
(0x56523ad8c420,0xc422e9e6e0)
Error: error pulling image "quay.io/metalkube/metalkube-ironic-inspector": Invalid image name "quay.io/metalkube/metalkube-ironic-inspector", expected colon-separated transport:reference
make: *** [ironic] Error 125

**Comment by russellb** [comment]
Did this happen again? I see on status.quay.io that there was some maintenance yesterday.

**Comment by gklein** [comment]
I was able to deploy a system and didn't see this error.

**Comment by chunfuwen** [comment]
I just finished new install, the issue is not reproduced, close it.
