### ISSUE TITLE
iptables created at step02 dont survive reboot

### ISSUE THREAD

**Issue by karmab** [openshift-metal3/dev-scripts#478]
**Describe the bug**
iptables created at step02 dont survive reboot

**To Reproduce**
Steps to reproduce the behavior, please include *all* details about the dev-scripts version (git commit SHA), any local variable overrides or other customizations, and whether you're deploying on VMs or Baremetal.
run step02 from dev scripts. reboot the helper node. cry

**Expected/observed behavior**
A clear and concise description of what you expected to happen and what went wrong, include details, and please try to look at relevant logs, to help us resolve the issue faster.

See https://github.com/openshift/installer/blob/master/docs/user/troubleshooting.md for some helpful steps to diagnose installer issues - please include details of any commands run here so we can gather clues to help identify the problem.

**Additional context**
Add any other context about the problem here, links to related issues etc.

**Comment by bfournie** [comment]
We should be creating the iptables rules now within the respective containers after this last change to rundnsmasq - https://github.com/metal3-io/ironic-image/commit/17dc7b2f8692b580a9427880047cb5d2f73ab2d6. 

I would expect this would run after container restarted.  Are you using an image with this change?

**Comment by russellb** [comment]
This was partially resolved when rhel8 support was added, as we used firewall-cmd to add the rules there.  We need to test using the same commands for centos7 envs to make sure it works there, too.  Then we can remove the platform conditionals around those commands.
