### ISSUE TITLE
make clean does not remove any extra workers VMs 

### ISSUE THREAD

**Issue by gklein** [openshift-metal3/dev-scripts#487]
**Describe the bug**
When deploying a cluster with more than one worker, "make clean" does not remove any extra workers VM, just the first (default) one.

**To Reproduce**

*Deploy a cluster with 3 workers + 10gb extra disk for both masters and workers
*git rev-parse HEAD
2975d40
*export VM_NODES_FILE=~kni/metalkube-nodes.yml
```
20,29c20
<   - name: openshift_worker_1
<     flavor: openshift_worker
<     virtualbmc_port: 6234
<
<   - name: openshift_worker_2
<     flavor: openshift_worker
<     virtualbmc_port: 6235
<
<
< node_count: 6
---
> node_count: 4
36,37c27
<     extradisks_size: 10G
<     extradisks: true
---
>     extradisks: false
43,44c33
<     extradisks_size: 10G
<     extradisks: true
---
>     extradisks: false
```
* Run "make clean"

**Expected/observed behavior**
One workers VM is removed, but 2 others are still exist. 

```
$ sudo virsh list --all
 Id    Name                           State
----------------------------------------------------
 20    openshift_worker_2             running
 -     openshift_worker_1             shut off
```

All workers VMs that appears in $VM_NODES_FILE, should be removed with "make clean".

**Comment by hardys** [comment]
Thanks, this is because we don't pass the VM_NODES_FILE to ansible in the `host_cleanup.sh`, which is easily fixed, but I'm working on a different approach which will remove VM_NODES_FILE and template the data dynamically, which should also solve this problem.
