### ISSUE TITLE
15 firing alerts after installation, mostly etcdHighNumberOfFailedGRPCRequests

### ISSUE THREAD

**Issue by jhutar** [openshift-metal3/dev-scripts#491]
**Describe the bug**
After installation, I can see 15 firing alerts:

AL - etcdHighNumberOfFailedGRPCRequests
etcd cluster "etcd": 100% of requests for Watch failed on etcd instance 192.168.111.20:9979.
Firing Since Apr 30, 11:29 am
Warning

AL - etcdHighNumberOfFailedGRPCRequests
etcd cluster "etcd": 100% of requests for Watch failed on etcd instance 192.168.111.21:9979.
Firing Since Apr 30, 3:41 pm
Warning

AL - etcdHighNumberOfFailedGRPCRequests
etcd cluster "etcd": 100% of requests for Watch failed on etcd instance 192.168.111.22:9979.
Firing Since Apr 30, 3:07 pm
Warning

AL - etcdHighNumberOfFailedGRPCRequests
etcd cluster "etcd": 100% of requests for Watch failed on etcd instance 192.168.111.21:9979.
Firing Since Apr 30, 3:41 pm
Critical

AL - etcdHighNumberOfFailedGRPCRequests
etcd cluster "etcd": 100% of requests for Watch failed on etcd instance 192.168.111.20:9979.
Firing Since Apr 30, 11:29 am
Critical

AL - etcdHighNumberOfFailedGRPCRequests
etcd cluster "etcd": 100% of requests for Watch failed on etcd instance 192.168.111.22:9979.
Firing Since Apr 30, 3:07 pm
Critical

AL - Watchdog
This is an alert meant to ensure that the entire alerting pipeline is functional. This alert is always firing, therefore it should always be firing in Alertmanager and always fire against a receiver. There are integrations with various notification mechanisms that send a notification when this alert is not firing. For example the "DeadMansSnitch" integration in PagerDuty.
Firing Since Apr 30, 11:26 am
None

AL - TelemeterClientDown
TelemeterClient has disappeared from Prometheus target discovery.
Firing Since Apr 30, 11:26 am
Critical

AL - TargetDown
100% of the sdn targets are down.
Firing Since Apr 30, 11:26 am
Warning

AL - TargetDown
100% of the kube-controller-manager targets are down.
Firing Since Apr 30, 11:29 am
Warning

AL - KubePodCrashLooping
Pod openshift-kni-infra/haproxy-master-0 (haproxy-monitor) is restarting 1.25 times / 5 minutes.
Firing Since Apr 30, 11:31 am
Critical

AL - KubePodCrashLooping
Pod openshift-kni-infra/haproxy-master-1 (haproxy-monitor) is restarting 0.83 times / 5 minutes.
Firing Since Apr 30, 11:31 am
Critical

AL - KubePodCrashLooping
Pod openshift-kni-infra/haproxy-master-2 (haproxy-monitor) is restarting 0.83 times / 5 minutes.
Firing Since Apr 30, 11:31 am
Critical

AL - KubeDeploymentReplicasMismatch
Deployment openshift-operator-lifecycle-manager/packageserver has not matched the expected number of replicas for longer than an hour.
Firing Since Apr 30, 11:27 am
Critical

AL - KubeControllerManagerDown
KubeControllerManager has disappeared from Prometheus target discovery.
Firing Since Apr 30, 11:26 am
Critical

**To Reproduce**
Install as per dev-scripts readme and navigate to https://kubevirt-web-ui.apps.ostest.test.metalkube.org/monitoring/alerts?orderBy=desc&sortBy=Name

**Expected/observed behavior**
There shouldn't be any firing alerts.

**Additional context**
All operators seem healthy:

```
$ oc --config /home/kni/dev-scripts/ocp/auth/kubeconfig get clusteroperators --all-namespaces --output wide
NAME                                 VERSION                        AVAILABLE   PROGRESSING   FAILING   SINCE
authentication                       4.0.0-0.ci-2019-04-17-133604   True        False         False     5h6m
cloud-credential                     4.0.0-0.ci-2019-04-17-133604   True        False         False     5h40m
cluster-autoscaler                   4.0.0-0.ci-2019-04-17-133604   True        False         False     5h40m
console                              4.0.0-0.ci-2019-04-17-133604   True        False         False     5h10m
dns                                  4.0.0-0.ci-2019-04-17-133604   True        False         False     5h39m
image-registry                       4.0.0-0.ci-2019-04-17-133604   True        False         False     5h15m
ingress                              4.0.0-0.ci-2019-04-17-133604   True        False         False     5h15m
kube-apiserver                       4.0.0-0.ci-2019-04-17-133604   True        False         False     5h20m
kube-controller-manager              4.0.0-0.ci-2019-04-17-133604   True        False         False     5h35m
kube-scheduler                       4.0.0-0.ci-2019-04-17-133604   True        False         False     5h36m
machine-api                          4.0.0-0.ci-2019-04-17-133604   True        False         False     5h40m
machine-config                       4.0.0-0.ci-2019-04-17-133604   True        False         False     5h39m
marketplace                          4.0.0-0.ci-2019-04-17-133604   True        False         False     5h15m
monitoring                           4.0.0-0.ci-2019-04-17-133604   True        False         False     5h12m
network                              4.0.0-0.ci-2019-04-17-133604   True        False         False     5h40m
node-tuning                          4.0.0-0.ci-2019-04-17-133604   True        False         False     5h15m
openshift-apiserver                  4.0.0-0.ci-2019-04-17-133604   True        False         False     5h20m
openshift-controller-manager         4.0.0-0.ci-2019-04-17-133604   True        False         False     5h37m
openshift-samples                    4.0.0-0.ci-2019-04-17-133604   True        False         False     5h17m
operator-lifecycle-manager           4.0.0-0.ci-2019-04-17-133604   True        False         False     5h38m
operator-lifecycle-manager-catalog   4.0.0-0.ci-2019-04-17-133604   True        False         False     5h38m
service-ca                           4.0.0-0.ci-2019-04-17-133604   True        False         False     5h39m
service-catalog-apiserver            4.0.0-0.ci-2019-04-17-133604   True        False         False     5h15m
service-catalog-controller-manager   4.0.0-0.ci-2019-04-17-133604   True        False         False     5h15m
storage                              4.0.0-0.ci-2019-04-17-133604   True        False         False     5h15m
```

All pods seem OK as well:

[oc_get_pods_A.log](https://github.com/openshift-metal3/dev-scripts/files/3131715/oc_get_pods_A.log)

But there is lots of errors like this:

```
$ oc --config /home/kni/dev-scripts/ocp/auth/kubeconfig logs pods/etcd-member-master-2 -n kube-system --all-containers | grep -i error | sort -R | tail -n 3
2019-04-30 09:33:46.929447 I | embed: rejected connection from "192.168.111.22:39362" (error "remote error: tls: bad certificate", ServerName "etcd-0.ostest.test.metalkube.org")
2019-04-30 09:25:06.671143 I | embed: rejected connection from "192.168.111.20:42064" (error "remote error: tls: bad certificate", ServerName "etcd-0.ostest.test.metalkube.org")
2019-04-30 08:57:14.892101 I | embed: rejected connection from "127.0.0.1:58498" (error "tls: failed to verify client's certificate: x509: certificate specifies an incompatible key usage", ServerName "")
```

Full output is in [logs_pods_etcd_member_master_2.log](https://github.com/openshift-metal3/dev-scripts/files/3131744/logs_pods_etcd_member_master_2.log) (it is same for `etcd-member-master-2` and `-0`).

**Comment by russellb** [comment]
We have now rebased to a much newer version. Please try again and see if this is still an issue. THe next step would most likely be to file this issue elsewhere though as it doesn’t seem install related.

**Comment by jhutar** [comment]
Hello @russellb . I have installed new version and when browse to https://kubevirt-web-ui.apps.ostest.test.metalkube.org/monitoring/alerts I get "Error Loading : NetworkError when attempting to fetch resource.". Is this page supposed to work?

**Comment by dhellmann** [comment]
Is this still an issue?

**Comment by hardys** [comment]
Closing this as stale since there was no reply to the previous comment from Doug
