### ISSUE TITLE
Deploy fails with:  failed to initialize the cluster: Working towards 4.0.0-0.ci-2019-04-17-133604: 98% complete, waiting on console, monitoring: timed out waiting for the condition

### ISSUE THREAD

**Issue by dantrainor** [openshift-metal3/dev-scripts#493]
**Describe the bug**
Consistently seeing failures of $subject.  

**To Reproduce**
git pull https://github.com/openshift-metal3/dev-scripts
make

**Expected/observed behavior**

I see pods failing, or stuck in ContainerCreating.  There is one pod with an OOMkilled status.  Interesting points are that there are also two pods with what appear to be an excessive number of Restarts with a CrashLoopBackOff status:

[rhhi@dev01 dev-scripts]$ oc get pod --all-namespaces | grep -ve Running -ve Completed
NAMESPACE                                               NAME                                                              READY   STATUS              RESTARTS   AGE
openshift-console                                       console-664bb6b7d5-9qqv2                                          0/1     CrashLoopBackOff    19         90m
openshift-kni-infra                                     haproxy-master-0                                                  1/2     CrashLoopBackOff    24         98m
openshift-kni-infra                                     haproxy-master-2                                                  1/2     CrashLoopBackOff    27         98m
openshift-kube-controller-manager                       installer-2-master-0                                              0/1     OOMKilled           0          98m
openshift-kube-controller-manager                       installer-3-master-2                                              0/1     ContainerCreating   0          97m
openshift-monitoring                                    node-exporter-hsnfc                                               0/2     ContainerCreating   0          97m

I also see 'console' and 'monitor' failing to become available:

[rhhi@dev01 dev-scripts]$ oc get clusteroperator
NAME                                 VERSION                        AVAILABLE   PROGRESSING   FAILING   SINCE
authentication                       4.0.0-0.ci-2019-04-17-133604   True        False         False     86m
cloud-credential                     4.0.0-0.ci-2019-04-17-133604   True        False         False     111m
cluster-autoscaler                   4.0.0-0.ci-2019-04-17-133604   True        False         False     111m
console                              4.0.0-0.ci-2019-04-17-133604   False       True          False     96m
dns                                  4.0.0-0.ci-2019-04-17-133604   True        False         False     111m
image-registry                       4.0.0-0.ci-2019-04-17-133604   True        False         False     99m
ingress                              4.0.0-0.ci-2019-04-17-133604   True        False         False     96m
kube-apiserver                       4.0.0-0.ci-2019-04-17-133604   True        False         False     108m
kube-controller-manager              4.0.0-0.ci-2019-04-17-133604   True        True          False     108m
kube-scheduler                       4.0.0-0.ci-2019-04-17-133604   True        False         False     108m
machine-api                          4.0.0-0.ci-2019-04-17-133604   True        False         False     111m
machine-config                       4.0.0-0.ci-2019-04-17-133604   True        False         False     111m
marketplace                          4.0.0-0.ci-2019-04-17-133604   True        False         False     96m
monitoring                                                          False       True          True      97m
network                              4.0.0-0.ci-2019-04-17-133604   True        False         False     112m
node-tuning                          4.0.0-0.ci-2019-04-17-133604   True        False         False     102m
openshift-apiserver                  4.0.0-0.ci-2019-04-17-133604   True        False         False     98m
openshift-controller-manager         4.0.0-0.ci-2019-04-17-133604   True        False         False     90m
openshift-samples                    4.0.0-0.ci-2019-04-17-133604   True        False         False     95m
operator-lifecycle-manager           4.0.0-0.ci-2019-04-17-133604   True        False         False     110m
operator-lifecycle-manager-catalog   4.0.0-0.ci-2019-04-17-133604   True        False         False     110m
service-ca                           4.0.0-0.ci-2019-04-17-133604   True        False         False     111m
service-catalog-apiserver            4.0.0-0.ci-2019-04-17-133604   True        False         False     94m
service-catalog-controller-manager   4.0.0-0.ci-2019-04-17-133604   True        False         False     102m
storage                              4.0.0-0.ci-2019-04-17-133604   True        False         False     102m

'get clusterversion' gives some curious output, specifically about "unknown version":

[rhhi@dev01 dev-scripts]$ oc get clusterversion -oyaml
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: ClusterVersion
  metadata:
    creationTimestamp: "2019-04-30T18:38:58Z"
    generation: 1
    name: version
    resourceVersion: "22244"
    selfLink: /apis/config.openshift.io/v1/clusterversions/version
    uid: 3722f10e-6b77-11e9-b94a-2232ce5173ca
  spec:
    channel: stable-4.0
    clusterID: b855c01f-3bec-4250-adf1-07dacfc5acb5
    upstream: https://api.openshift.com/api/upgrades_info/v1/graph
  status:
    availableUpdates: null
    conditions:
    - lastTransitionTime: "2019-04-30T18:39:07Z"
      status: "False"
      type: Available
    - lastTransitionTime: "2019-04-30T19:15:41Z"
      message: 'Some cluster operators are still updating: console, monitoring'
      reason: ClusterOperatorsNotAvailable
      status: "True"
      type: Failing
    - lastTransitionTime: "2019-04-30T18:39:07Z"
      message: 'Unable to apply 4.0.0-0.ci-2019-04-17-133604: some cluster operators
        have not yet rolled out'
      reason: ClusterOperatorsNotAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2019-04-30T18:39:07Z"
      message: 'Unable to retrieve available updates: unknown version 4.0.0-0.ci-2019-04-17-133604'
      reason: RemoteFailed
      status: "False"
      type: RetrievedUpdates
    desired:
      image: registry.svc.ci.openshift.org/ocp/release@sha256:18be381c1fa7a5ade05a43a4b9359f28c6b13462514b2810b886b8275c80a79c
      version: 4.0.0-0.ci-2019-04-17-133604
    history:
    - completionTime: null
      image: registry.svc.ci.openshift.org/ocp/release@sha256:18be381c1fa7a5ade05a43a4b9359f28c6b13462514b2810b886b8275c80a79c
      startedTime: "2019-04-30T18:39:07Z"
      state: Partial
      version: 4.0.0-0.ci-2019-04-17-133604
    observedGeneration: 1
    versionHash: c3Oslo2fEgA=
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

I wonder if the $OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE image is no longer available in CI?  But if that were the case, I would expect more things to break, not just two random pods?

**Comment by dantrainor** [comment]
I did see https://github.com/openshift-metal3/dev-scripts/issues/365 but no resolution of what caused this, however the issue provides some further documentation to support this.

**Comment by dantrainor** [comment]
I think I managed to fix it, notes in a PR by @dhellmann  that I found after starting some of the same work locally, located at https://github.com/openshift-metal3/dev-scripts/pull/427

**Comment by dantrainor** [comment]
I'll pull @dhellmann 's PR and hack on it locally to make this stick.

**Comment by russellb** [comment]
We've udpated to a newer version of OpenShift since this report, so please open a new bug if you see problems with what's current
