### ISSUE TITLE
Sometimes there are multiple instances of Iptable rule for redirecting API traffic to HA-PROXY

### ISSUE THREAD

**Issue by yboaron** [openshift-metal3/dev-scripts#528]
**Describe the bug**
To LB OCP API traffic, an iptable rule redirects API port traffic (port 6443) to LB frontend port (7443).

Sometimes we can see multiple instances of this rule.
[core@master-2 ~]$ sudo iptables -w 10 -L PREROUTING -n -t nat --line-numbers | grep OCP_API_LB_REDIRECT
1 REDIRECT tcp – 0.0.0.0/0 192.168.111.5 tcp dpt:6443 /* OCP_API_LB_REDIRECT */ redir ports 7443
2 REDIRECT tcp – 0.0.0.0/0 192.168.111.5 tcp dpt:6443 /* OCP_API_LB_REDIRECT */ redir ports 7443
[core@master-2 ~]$

**To Reproduce**

To reproduce this bug I forced few times set and move of the API VIP in a specific master node.

**Expected/observed behavior**
Single iptable rule for redirecting traffic towards OCP API LB.

**Additional context**
Checking the logs of the  haproxy-monitor pod, I found the following error:

+ declare -r lb_port=7443
++ iptables -L PREROUTING -n -t nat --line-numbers
++ awk '/OCP_API_LB_REDIRECT/ {print $1}'
++ tac
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
+ declare -r rules=
+ [[ -z '' ]]
+ echo 'Setting prerouting rule from 192.168.111.5:6443 to port 7443'
Setting prerouting rule from 192.168.111.5:6443 to port 7443
+ iptables -t nat -I PREROUTING --src 0/0 --dst 192.168.111.5 -p tcp --dport 6443 -j REDIRECT --to-ports 7443 -m comment --comment OCP_API_LB_REDIRECT
+ true

**Comment by hardys** [comment]
Closed via #527
