### ISSUE TITLE
machine-api is failing on 4.1.0 rc.3

### ISSUE THREAD

**Issue by stbenjam** [openshift-metal3/dev-scripts#537]
machine-api fails to come up on latest rebase PR's:

```
openshift-machine-api                                   machine-api-controllers-54586c8cb9-759kz                          2/3     CrashLoopBackOff   8          19m
```

```
# oc logs machine-api-controllers-54586c8cb9-759kz -n openshift-machine-api -c controller-manager

2019/05/15 15:39:21 Registering Components.

2019/05/15 15:39:21 no matches for kind "MachineDeployment" in version "machine.openshift.io/v1beta1
```

-----

TODO checklist (CAPBM is cluster-api-provider-baremetal)

- [x] Update master of openshift/CAPBM to latest from openshift/cluster-api branch branch used for 4.1 -- https://github.com/openshift/cluster-api-provider-baremetal/pull/23
- [x] Backport ^^^ to release-4.1 branch of openshift/CAPBM -- https://github.com/openshift/cluster-api-provider-baremetal/pull/24
- [x] Move master of openshift/CAPBM to openshift/cluster-api branch used for 4.2 --- https://github.com/openshift/cluster-api-provider-baremetal/pull/25
- [x] https://github.com/openshift-metal3/kni-installer/pull/80

**Comment by russellb** [comment]
I'm on it.

**Comment by russellb** [comment]
Here's the deal ...

cluster-api-provider-baremetal is integrated into OpenShift, but since we've been using a pinned release, we haven't tested it with the latest version of OpenShift until now.  It appears it went stale and needs updates.  I'm working on that now.

This means that it will remain broken until we get a fix into a newer release of OpenShift.  To use this OpenShift release, we'll have to hack up dev-scripts to run a custom image of cluster-api-provider-baremetal.  To do that, we'll have to first tell CVO to stop managing machine-api-operator.  It's far from ideal.  There's some hints about this in here: https://github.com/openshift-metal3/dev-scripts/blob/master/docs/custom-mao-and-capbm.md

I'm going to fix cluster-api-provider-baremetal first, and then I can help with how to layer it on a release with a broken cluster-api-provider-baremetal ...

**Comment by markmc** [comment]
> This means that it will remain broken until we get a fix into a newer release of OpenShift. To use this OpenShift release, we'll have to hack up dev-scripts to run a custom image of cluster-api-provider-baremetal. 

Well, we have the ability to produce our own release payloads - we could totally add a custom image for this as a temporary workaround

i.e. we can build on #401

**Comment by russellb** [comment]
> > This means that it will remain broken until we get a fix into a newer release of OpenShift. To use this OpenShift release, we'll have to hack up dev-scripts to run a custom image of cluster-api-provider-baremetal.
> 
> Well, we have the ability to produce our own release payloads - we could totally add a custom image for this as a temporary workaround
> 
> i.e. we can build on #401

Oh, awesome.  That sounds much nicer.  I'll follow up once I have a fixed version available.

**Comment by russellb** [comment]
First PR is up.  https://github.com/openshift/cluster-api-provider-baremetal/pull/23

I'll start a checklist at the top of this issue.

**Comment by russellb** [comment]
I'm going to continue tracking the changes needed in openshift in this issue, but to unblock testing, I pushed a fixed image here: `quay.io/openshift-metal3/baremetal-machine-controllers`.  So, if we build a new release image based on `4.1.0-rc3` that replaced the baremetal machine controllers image with that one, you should get past this problem.

**Comment by markmc** [comment]
Ok, I've built registry.svc.ci.openshift.org/kni/release:4.1.0-rc.3-kni.0 with this baremetal-machine-controllers image

Details on the build here: https://gist.github.com/markmc/f8a78d7cea7252a9e0f29dadcfaa1253

Haven't tested yet

**Comment by russellb** [comment]
Our workaround is in place in a custom release, and all of the appropriate fixes have landed in openshift/cluster-api-provider-baremetal, so I'm closing this as resolved.

**Comment by russellb** [comment]
To fix this last problem, we need the following change in kni-installer for the baremetal platform: https://github.com/openshift/installer/commit/be7bf8ec27c7c91be43eac41346da1730c6e3d31

**Comment by russellb** [comment]
> To fix this last problem, we need the following change in kni-installer for the baremetal platform: [openshift/installer@be7bf8e](https://github.com/openshift/installer/commit/be7bf8ec27c7c91be43eac41346da1730c6e3d31)

I'll send a kni-installer PR for this

**Comment by russellb** [comment]
Fix here: https://github.com/openshift-metal3/kni-installer/pull/80
