### ISSUE TITLE
api-int should not be a required external DNS record

### ISSUE THREAD

**Issue by cybertron** [openshift-metal3/dev-scripts#538]
As part of the 4.1 rebase, we need to add support for the api-int DNS name. Unfortunately, because this is used during ignition (before we configure nodes to point at coredns) just adding a static entry in coredns is not sufficient. #523 is adding it to the libvirt dnsmasq, but this essentially makes it a required external record. Since it's actually for internal use only, we shouldn't be requiring that.

This issue is to track the tech debt associated with api-int and provide a reference for the work to remove the external DNS requirement. Currently the plan is to point ignition directly at the VIP and then switch to using api-int once we've configured the nodes to point at coredns.

**Comment by cybertron** [comment]
For further information on api-int, see https://bugzilla.redhat.com/show_bug.cgi?id=1685704

**Comment by cybertron** [comment]
This actually isn't completed until at least https://github.com/openshift-metal3/kni-installer/pull/82 merges. Preferrably after #560 merges too though to verify that the external record is no longer in use.

**Comment by hardys** [comment]
> This actually isn't completed until at least [openshift-metal3/kni-installer#82](https://github.com/openshift-metal3/kni-installer/pull/82) merges. Preferrably after #560 merges too though to verify that the external record is no longer in use.

Ack thanks, I think it got auto-closed due to the commit message, I'm testing openshift-metal3/kni-installer#82  and #560 now so we can hopefully get those merged as well

**Comment by cybertron** [comment]
Cool, thanks.

/me misses Related-Bug from OpenStack ;-)
