### ISSUE TITLE
Installation fails: Failed connect to images.rdoproject.org

### ISSUE THREAD

**Issue by itzikb-redhat** [openshift-metal3/dev-scripts#543]
My installation fails with the following error:
```
/opt/dev-scripts/ironic/html/images ~/dev-scripts
++ '[' '!' -f rhcos-410.8.20190412.1-openstack.qcow2 ']'
++ curl --insecure --compressed -L -o rhcos-410.8.20190412.1-openstack.qcow2 https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/ootpa/410.8.20190412.1//rhcos-410.8.20190412.1-openstack.qcow2
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                Dload  Upload   Total   Spent    Left  Speed
100   161  100   161    0     0    207      0 --:--:-- --:--:-- --:--:--   207
100  733M  100  733M    0     0  6956k      0  0:01:47  0:01:47 --:--:-- 4251k
++ '[' '!' -f ironic-python-agent.initramfs ']'
++ curl --insecure --compressed -L https://images.rdoproject.org/master/rdo_trunk/current-tripleo-rdo/ironic-python-agent.tar
++ tar -xf -
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                Dload  Upload   Total   Spent    Left  Speed
 0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0curl: (7) Failed connect to images.rdoproject.org:443; No route to host
```
After the installation failed I had no problem getting the file.

**Comment by hardys** [comment]
`curl: (7) Failed connect to images.rdoproject.org:443; No route to host` shows you had a (presumably temporary) network outage, so I'm a little unclear what you expected to happen here?

AFAICS the error message is clear, and you retried later and it worked?

I see you pushed a PR with a connect timeout, but I'm not really sure that should be needed?

**Comment by itzikb-redhat** [comment]
Hi,
In case there is a load on the server and it takes longer to response - it may help to have the curl wait longer.

**Comment by hardys** [comment]
But "no route to host" isn't a server timeout?  It means connectivity to the host was impossible, e.g there was a network outage if it's temporary, or a client-side misconfiguration if it's permanent.

**Comment by itzikb-redhat** [comment]
Yes - in this case it's a temporary network outage. I case of permanent network issue there is not reason to wait.

**Comment by hardys** [comment]
Ok thanks, I'll close this then as I think it's not a bug and the existing curl error is sufficient
