### ISSUE TITLE
terraform.EvalApplyPost, err: 1 error occurred

### ISSUE THREAD

**Issue by chunfuwen** [openshift-metal3/dev-scripts#569]
when install ocp, I met below error
'''
level=debug msg="2019/05/24 16:17:47 [DEBUG] apply: libvirt_domain.bootstrap: executing Apply"
level=debug msg="module.bootstrap.libvirt_domain.bootstrap: Creation complete after 2s (ID: 133bbc98-08d8-4d83-a3c7-a4976b1a6f3f)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (10s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.1: Still creating... (10s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (10s elapsed)"
level=debug msg="2019/05/24 16:17:56 [ERROR] root.masters: eval: *terraform.EvalApplyPost, err: 1 error occurred:"
level=debug msg="\t* ironic_node_v1.openshift-master.1: Expected HTTP response code [202] when accessing [PUT http://localhost:6385/v1/nodes/74736478-ef0c-4356-b9ec-9c69e158c802/states/provision], but got 409 instead"
level=debug msg="{\"error_message\": \"{\\\"debuginfo\\\": null, \\\"faultcode\\\": \\\"Client\\\", \\\"faultstring\\\": \\\"Node 74736478-ef0c-4356-b9ec-9c69e158c802 is locked by host gold-4s-a.tpb.lab.eng.brq.redhat.com, please retry after the current operation is completed.\\\"}\"}"
level=debug
level=debug msg="2019/05/24 16:17:56 [ERROR] root.masters: eval: *terraform.EvalSequence, err: 1 error occurred:"
level=debug msg="\t* ironic_node_v1.openshift-master.1: Expected HTTP response code [202] when accessing [PUT http://localhost:6385/v1/nodes/74736478-ef0c-4356-b9ec-9c69e158c802/states/provision], but got 409 instead"
level=debug msg="{\"error_message\": \"{\\\"debuginfo\\\": null, \\\"faultcode\\\": \\\"Client\\\", \\\"faultstring\\\": \\\"Node 74736478-ef0c-4356-b9ec-9c69e158c802 is locked by host gold-4s-a.tpb.lab.eng.brq.redhat.com, please retry after the current operation is completed.\\\"}\"}"
level=debug
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (20s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (20s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (30s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (30s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (40s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (40s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (50s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (50s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (1m0s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (1m0s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (1m10s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (1m10s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (1m20s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (1m20s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (1m30s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (1m30s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (1m40s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (1m40s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (1m50s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (1m50s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (2m0s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (2m0s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (2m10s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (2m10s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (2m20s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (2m20s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (2m30s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (2m30s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (2m40s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (2m40s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (2m50s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (2m50s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (3m0s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (3m0s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (3m10s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (3m10s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (3m20s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (3m20s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (3m30s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (3m30s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (3m40s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (3m40s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (3m50s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (3m50s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (4m0s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (4m0s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (4m10s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (4m10s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (4m20s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (4m20s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (4m30s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (4m30s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (4m40s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (4m40s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.2: Still creating... (4m50s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master.0: Still creating... (4m50s elapsed)"
level=debug msg="module.masters.ironic_node_v1.openshift-master[0]: Creation complete after 4m55s (ID: c2a79d38-60d7-4c87-ad54-f77b2031869c)"
level=debug msg="module.masters.ironic_node_v1.openshift-master[2]: Creation complete after 4m57s (ID: e7f3db23-c9c5-4784-9d8c-3d2e9cd16658)"
level=error
level=error msg="Error: Error applying plan:"
level=error
level=error msg="1 error occurred:"
level=error msg="\t* module.masters.ironic_node_v1.openshift-master[1]: 1 error occurred:"
level=error msg="\t* ironic_node_v1.openshift-master.1: Expected HTTP response code [202] when accessing [PUT http://localhost:6385/v1/nodes/74736478-ef0c-4356-b9ec-9c69e158c802/states/provision], but got 409 instead"
level=error msg="{\"error_message\": \"{\\\"debuginfo\\\": null, \\\"faultcode\\\": \\\"Client\\\", \\\"faultstring\\\": \\\"Node 74736478-ef0c-4356-b9ec-9c69e158c802 is locked by host gold-4s-a.tpb.lab.eng.brq.redhat.com, please retry after the current operation is completed.\\\"}\"}"
level=error
level=error
level=error
level=error
level=error
level=error msg="Terraform does not automatically rollback in the face of errors."
level=error msg="Instead, your Terraform state file has been partially updated with"
level=error msg="any resources that successfully completed. Please address the error"
level=error msg="above and apply again to incrementally change your infrastructure."
level=error
level=error
level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"
make: *** [ocp_run] Error 1

'''

**Comment by stbenjam** [comment]
I've seen this happen once or twice.  Ironic indicates a node has changed some state that terraform recognizes as a cue to continue, but the node isn't really available as something else has a lock on it.  The only thing I've been able to do is `make clean` and try again.  Is it reproducible by any chance?

**Comment by chunfuwen** [comment]
I met this when export NUM_WORKERS="2". but can not observe it under export NUM_WORKERS="1". Not sure whether it is related to Numbers of worker nodes

**Comment by hardys** [comment]
> I met this when export NUM_WORKERS="2". but can not observe it under export NUM_WORKERS="1". Not sure whether it is related to Numbers of worker nodes

The error is during the master deploy via terraform, so I don't think this is related (workers are deployed via a different mechanism after the cluster bootstrap has deployed the master nodes)

**Comment by hardys** [comment]
@stbenjam perhaps this should be a bug against terraform-provider-ironic or gophercloud, where we could consider some retry when locked logic to work around this?

**Comment by stbenjam** [comment]
We can work around it in terraform if we get a 409; I just saw this on CI, http://10.8.144.11:8080/job/dev-tools/696/:

```
2019-06-03 12:39:33.376 67 DEBUG ironic.common.json_rpc.server [req-39c9a23e-d992-40c7-8a41-731f9c62bae1 - - - - -] RPC error NodeLocked: Node 5c27b288-16d6-4dbe-acd6-a813f90476b8 is locked by host host10.beaker.tripleo.lab.eng.rdu2.redhat.com, please retry after the current operation is completed. _handle_error /usr/lib/python2.7/site-packages/ironic/common/json_rpc/server.py:142
```

I wonder if we shouldn't set retry_interval higher, because the conductor itself has a retry mechanism:

```
2019-06-03 12:38:44.017 67 DEBUG oslo_service.service [-] conductor.node_locked_retry_attempts = 3 log_opt
_values /usr/lib/python2.7/site-packages/oslo_config/cfg.py:2589
2019-06-03 12:38:44.017 67 DEBUG oslo_service.service [-] conductor.node_locked_retry_interval = 1 log_opt_values /usr/lib/python2.7/site-packages/oslo_config/cfg.py:2589
```

**Comment by stbenjam** [comment]
We have fixed the problems with 409 conflict errors in https://github.com/openshift-metal3/terraform-provider-ironic/pull/33, these should not happen anymore.
