### ISSUE TITLE
getting "CNV is in error state" after `make` + `09_deploy_kubevirt.sh` + `10_deploy_rook.sh`

### ISSUE THREAD

**Issue by jhutar** [openshift-metal3/dev-scripts#575]
**Describe the bug**
On https://kubevirt-web-ui.apps.ostest.test.metalkube.org/dashboards -> Cluster Health -> See all it says "CNV is in error state": https://coreos.slack.com/archives/CFP6ST0A3/p1559072496163300

**To Reproduce**
1. `make` + `09_deploy_kubevirt.sh` + `10_deploy_rook.sh`
2. Check https://kubevirt-web-ui.apps.ostest.test.metalkube.org/dashboards

**Expected/observed behavior**
Should be working.

**Additional context**
Looking into `09_deploy_kubevirt.sh`, I have checked kubevirt-web-ui namespace and all looks good:

```
[kni@titan97 dev-scripts]$ oc --config /home/kni/dev-scripts/ocp/auth/kubeconfig get pods -n kubevirt-web-ui
NAME                                        READY   STATUS    RESTARTS   AGE
console-77bb8858d-dtxp4                     1/1     Running   0          89m
console-77bb8858d-m8c42                     1/1     Running   0          89m
kubevirt-web-ui-operator-7d5ff9d9db-47hnq   1/1     Running   0          90m
```

Any idea what shall I check please?

**Comment by karmab** [comment]
i was told today it relates to https://github.com/kubevirt/kubevirt/pull/2285 so we need a version of kubevirt which contains this fix

**Comment by karmab** [comment]
should be fixed by https://github.com/openshift-metal3/dev-scripts/pull/587

**Comment by russellb** [comment]
looks like this was fixed.

Note that this integration will be dropped from dev-scripts though - #603
