### ISSUE TITLE
Stop doing `sudo pip install`

### ISSUE THREAD

**Issue by dtantsur** [openshift-metal3/dev-scripts#584]
It's a well known no-go. Currently it replaces PyYAML with a much newer (3.* to 5.*) version, which has potential of breaking installed packages. We should either use virtualenv or `pip install --user`.

**Comment by hardys** [comment]
We could just install yq with go get seeing as we're already installing various go things for development https://mikefarah.github.io/yq/

Not sure about lolcat though, clearly we'll have to find a solution for that :D

**Comment by hardys** [comment]
Ok so short term we can go get yq, and install ruby from RPM then gem install lolcat.

Fairly soon the yq should be unnecessary though when we move the manifest/asset templating out of dev-scripts, ref https://github.com/openshift-metal3/dev-scripts/issues/561

**Comment by dtantsur** [comment]
May I dare ask if we really need lolcat so much? :)

**Comment by russellb** [comment]
heh, +1 to remove lolcat if it helps clean up our dependencies.

**Comment by hardys** [comment]
Ok lolcat removed via https://github.com/openshift-metal3/dev-scripts/issues/594, I'll push a pr that switches yq to go get later.

**Comment by hardys** [comment]
Ok just to follow up, that go based yq is `yq.v2` which isn't the same as the python tool we're using, which is just a wrapper for jq (the go one doesn't support the filtering features we need).

https://github.com/kislyuk/yq is the one we need, and even installing from source you need to do `pip install .` so the setuptools stuff will do the build/install, so I'd say lets leave this until the manifest stuff gets removed (hopefully soon)

**Comment by hardys** [comment]
This will be closed via https://github.com/openshift-metal3/dev-scripts/issues/561 so lets close this and track removing the short-term hacks that need yq there.

**Comment by dtantsur** [comment]
We could do `pip install --user`..

**Comment by hardys** [comment]
> We could do `pip install --user`..

Yeah, Ok reopened so feel free to push a PR if you'd like to go that way - I was just thinking pretty soon this will go away so it's probably not a priority.

**Comment by russellb** [comment]
There's no `pip` calls in dev-scripts anymore
