### ISSUE TITLE
Still waiting for the cluster to initialize: Multiple errors are preventing progress:\n* Cluster operator authentication has not yet reported success\n

### ISSUE THREAD

**Issue by chunfuwen** [openshift-metal3/dev-scripts#591]
it sound like the installation was stuck.
And the log output follow as below:
'''
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-rc.5-kni.1: 74% complete"
level=debug msg="Still waiting for the cluster to initialize: Working towards 4.1.0-rc.5-kni.1: 82% complete"
level=debug msg="Still waiting for the cluster to initialize: Multiple errors are preventing progress:\n* Cluster operator authentication has not yet reported success\n* Cluster operator image-registry has not yet reported success\n* Cluster operator ingress has not yet reported success\n* Cluster operator kube-scheduler is reporting a failure: NodeInstallerDegraded: 1 nodes are failing on revision 4:\nNodeInstallerDegraded: \nStaticPodsDegraded: nodes/master-1 pods/openshift-kube-scheduler-master-1 container=\"scheduler\" is not ready\nStaticPodsDegraded: pods \"openshift-kube-scheduler-master-0\" not found\nStaticPodsDegraded: pods \"openshift-kube-scheduler-master-2\" not found\n* Cluster operator marketplace has not yet reported success\n* Cluster operator monitoring has not yet reported success\n* Cluster operator node-tuning has not yet reported success\n* Cluster operator openshift-apiserver has not yet reported success\n* Cluster operator service-catalog-apiserver has not yet reported success\n* Cluster operator service-catalog-controller-manager has not yet reported success\n* Cluster operator storage has not yet reported success\n* Could not update deployment \"openshift-dns-operator/dns-operator\" (305 of 350)\n* Could not update oauthclient \"console\" (220 of 350): the server does not recognize this resource, check extension API servers\n* Could not update rolebinding \"openshift/cluster-samples-operator-openshift-edit\" (182 of 350): resource may have been deleted\n* Could not update servicemonitor \"openshift-apiserver-operator/openshift-apiserver-operator\" (346 of 350): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-authentication-operator/authentication-operator\" (321 of 350): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-controller-manager-operator/openshift-controller-manager-operator\" (349 of 350): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-image-registry/image-registry\" (327 of 350): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-kube-apiserver-operator/kube-apiserver-operator\" (337 of 350): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-kube-controller-manager-operator/kube-controller-manager-operator\" (340 of 350): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-kube-scheduler-operator/kube-scheduler-operator\" (343 of 350): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-operator-lifecycle-manager/olm-operator\" (267 of 350): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-service-catalog-apiserver-operator/openshift-service-catalog-apiserver-operator\" (330 of 350): the server does not recognize this resource, check extension API servers\n* Could not update servicemonitor \"openshift-service-catalog-controller-manager-operator/openshift-service-catalog-controller-manager-operator\" (333 of 350): the server does not recognize this resource, check extension API servers"
'''

**Comment by russellb** [comment]
Did it finish? There’s a lot of noise in the process, so it could have worked itself out if you wait long enough.

**Comment by chunfuwen** [comment]
Finally, it is done, but the noise really interrupt me.

**Comment by russellb** [comment]
Yeah, we have debug logging on by default.  It can be distracting, for sure, but helpful to see what happened if something really does go wrong.  Customer usage of the installer would see far less output.
