### ISSUE TITLE
Re-enable selinux on provisioning host

### ISSUE THREAD

**Issue by russellb** [openshift-metal3/dev-scripts#600]
01_install_requirements.sh disables selinux.  We need to get to where this is not required on the provisioning host.  This bug tracks removing this from dev-scripts.

**Comment by ch-stark** [comment]
did a test today without selinux disabled 
commented out:
#if selinuxenabled ; then
    # FIXME ocp-doit required this so leave permissive for now
    #sudo setenforce permissive
    #sudo sed -i "s/=enforcing/=permissive/g" /etc/selinux/config
#fi

and did't find issues

**Comment by russellb** [comment]
selinux is no longer disabled in dev-scripts
