### ISSUE TITLE
PersistentVolumeClaim using storageclass:rook-ceph-block pend for binding for long time

### ISSUE THREAD

**Issue by chunfuwen** [openshift-metal3/dev-scripts#605]
Steps:
1)deploy rook ceph by execute 09_deploy_kubevirt.sh, 10_deploy_rook.sh
2)Check storageclass :rook-ceph-block is ready
'''
[chwen@r640-u07 dev-scripts]$ oc get storageclass
NAME                        PROVISIONER          AGE
rook-ceph-block (default)   ceph.rook.io/block   24h
[chwen@r640-u07 dev-scripts]$ oc describe storageclass rook-ceph-block
Name:                  rook-ceph-block
IsDefaultClass:        Yes
Annotations:           storageclass.kubernetes.io/is-default-class=true
Provisioner:           ceph.rook.io/block
Parameters:            blockPool=rbd,clusterNamespace=openshift-storage,fstype=xfs
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Retain
VolumeBindingMode:     Immediate
Events:                <none>
'''
3)create one pvc using storageclass:rook-ceph-block
'''
oc create -f wcf_pvc.yaml
[chwen@r640-u07 dev-scripts]$ cat wcf_pvc.yaml 
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wcf-pvc
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
'''
4)check the pvc status, finding that they are long time pending
'''
[chwen@r640-u07 dev-scripts]$ oc get pvc
NAME             STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS      AGE
mysql-pv-claim   Pending                                      rook-ceph-block   15m
pvc1             Pending                                      rook-ceph-block   36m
wcf-pvc          Pending                                      rook-ceph-block   9m46s
wp-pv-claim      Pending                                      rook-ceph-block   15m

'''

**Comment by russellb** [comment]
rook is going to be dropped from dev-scripts, see #603 -- If you continue to have trouble with rook, I'd encourage you to follow up with the rook team.  Thanks!
