### ISSUE TITLE
Dev-scipts setup not working as described in documentaion

### ISSUE THREAD

**Issue by anmolsachan** [openshift-metal3/dev-scripts#614]
**Describe the bug**
Not being able to setup by following the docs. The ocp cluster installation never starts and the 06_create_cluster.sh just ends with : 
`
+ '[' y == y ']'
++ awk '{print $NF}'
+++ network_ip baremetal
+++ local network
+++ local rc
+++ network=baremetal
++++ sudo virsh net-dumpxml baremetal
++++ /root/dev-scripts/pyxpath //ip/@address -
+++ ip=192.168.111.1
+++ rc=0
+++ '[' 0 -ne 0 ']'
+++ echo 192.168.111.1
++ dig +noall +answer api.ostest.test.metalkube.org @192.168.111.1
+ API_VIP=reached
`

**To Reproduce**
Follow docs to reproduce

**Expected/observed behavior**
Openshift cluster should come up.

**Comment by hardys** [comment]
Thanks for the report, but we really need more information to help debug the cause - can you provide the logfile from dev-scripts/logs for the failing script, and details of your test environment, e.g VM/baremetal and the OS on the provisioning host?

**Comment by hardys** [comment]
Also please try running the dig manually, e.g:

```
$ dig +noall +answer api.ostest.test.metalkube.org @192.168.111.1
api.ostest.test.metalkube.org. 0 IN	A	192.168.111.5
```

the `reached` in your output looks wrong to me.

**Comment by anmolsachan** [comment]
The setup worked after some environment cleanup. Its was not a bug. Closing the issue.

**Comment by anmolsachan** [comment]
Used following to do the cleanup and Node restart.

```
#!/bin/bash

make clean
rm -rf ~/.cache/
rm -rf /tmp/*
rm -rf ~/go/src/github.com/*
rm -rf /opt/dev-scripts/*
rm -rf /var/lib/containers/*
yum reinstall podman
```
