### ISSUE TITLE
BM deployment fails with: "level=fatal msg="failed to fetch Master Machines: failed to load asset \"Install Config\": invalid \"install-config.yaml\" file: compute[0].replicas: Invalid value: -1: number of replicas must not be negative"

### ISSUE THREAD

**Issue by achuzhoy** [openshift-metal3/dev-scripts#626]
BM deployment fails with: "level=fatal msg="failed to fetch Master Machines: failed to load asset \"Install Config\": invalid \"install-config.yaml\" file: compute[0].replicas: Invalid value: -1: number of replicas must not be negative"

The masters and workers are all off. The bootstrap VM didn't even start yet:

+ timeout=20
+ shift 3
+ curl_opts='-H Accept: application/json -H Content-Type: application/json -H User-Agent: wait-for-json -H X-Auth-Token: fake-token'
+ echo -n 'Waiting for ironic to respond'
Waiting for ironic to respond++ date +%s
+ start_time=1560869114
+ jq .
+ curl -g -X GET http://localhost:6385//v1/nodes '-H Accept: application/json -H Content-Type: application/json -H User-Agent: wait-for-json -H X-Auth-Token: fake-token'
+ echo ' Success!'
 Success!
+ return 0
++ sudo podman ps
++ wc -l
++ grep -w -e 'ironic$' -e 'ironic-inspector$' -e dnsmasq -e httpd
+ '[' 4 '!=' 4 ']'
++ dirname ./06_create_cluster.sh
+ sudo systemd-run --on-active=30s --on-unit-active=1m --unit=fix_certs.service ./fix_certs.sh
Running timer as unit fix_certs.timer.
Will run service as unit fix_certs.service.
+ create_cluster ocp
+ local assets_dir
+ assets_dir=ocp
+ export TF_LOG=DEBUG
+ TF_LOG=DEBUG
+ cp ocp/install-config.yaml ocp/install-config.yaml.tmp
+ ocp//openshift-install --dir ocp --log-level=debug create manifests
level=debug msg="OpenShift Installer 9ecc1b53e8fd34b1987f6b7db25a253e1bdf656b-dirty"
level=debug msg="Built from commit 9ecc1b53e8fd34b1987f6b7db25a253e1bdf656b"
level=debug msg="Fetching \"Master Machines\"..."
level=debug msg="Loading \"Master Machines\"..."
level=debug msg="  Loading \"Cluster ID\"..."
level=debug msg="    Loading \"Install Config\"..."
level=debug msg="      Loading \"SSH Key\"..."
level=debug msg="      Loading \"Base Domain\"..."
level=debug msg="        Loading \"Platform\"..."
level=debug msg="      Loading \"Cluster Name\"..."
level=debug msg="        Loading \"Base Domain\"..."
level=debug msg="      Loading \"Pull Secret\"..."
level=debug msg="      Loading \"Platform\"..."
level=warning msg="There are no compute nodes specified. The cluster will not fully initialize without compute nodes."
level=fatal msg="failed to fetch Master Machines: failed to load asset \"Install Config\": invalid \"install-config.yaml\" file: compute[0].replicas: Invalid value: -1: number of replicas must not be negative"
(END)

[achuzhoy@achuzhoy ~]$ for i in {2..6}; do ipmitool -I lanplus -H r640-u0${i}-drac.qe1.kni.lab.eng.bos.redhat.com -U root -P calvin chassis power status; done
Chassis Power is off
Chassis Power is off
Chassis Power is off
Chassis Power is off
Chassis Power is off

**Comment by russellb** [comment]
Can you post the install-config.yaml that was generated and given to the installer?  Look in the ocp/ directory for it.

**Comment by hardys** [comment]
Also please post the full logs for the 06 script, in particular I want to see what NUM_WORKERS is set to.

**Comment by achuzhoy** [comment]
This was related to a wrong value set in automated deploy.
Closing.

Thanks and apologies.
