### ISSUE TITLE
module.masters.ironic_node_v1.openshift-master-host[2]: apply errored

### ISSUE THREAD

**Issue by bkunal** [openshift-metal3/dev-scripts#636]
**Describe the bug**
Create cluster fails i.e ./06_create_cluster.sh fails

**To Reproduce**
Steps were followed for Baremetal from https://github.com/openshift-metal3/dev-scripts.

Observed behavior**

level=debug msg="module.masters.ironic_node_v1.openshift-master-host[2]: Still creating... [30m50s elapsed]"
level=debug msg="module.masters.ironic_node_v1.openshift-master-host[1]: Still creating... [30m50s elapsed]"
level=debug msg="module.masters.ironic_node_v1.openshift-master-host[0]: Still creating... [30m50s elapsed]"
level=debug msg="2019/06/21 06:11:48 [DEBUG] module.masters.ironic_node_v1.openshift-master-host[2]: apply errored, but we're indicating that via the Error pointer rather than returning it: could not inspect: could not inspect node, node is currently 'inspect failed', last error was 'timeout reached while inspecting the node'"
level=debug msg="2019/06/21 06:11:48 [ERROR] module.masters: eval: *terraform.EvalApplyPost, err: could not inspect: could not inspect node, node is currently 'inspect failed', last error was 'timeout reached while inspecting the node'"
level=debug msg="2019/06/21 06:11:48 [ERROR] module.masters: eval: *terraform.EvalSequence, err: could not inspect: could not inspect node, node is currently 'inspect failed', last error was 'timeout reached while inspecting the node'"
level=debug msg="2019/06/21 06:11:48 [DEBUG] module.masters.ironic_node_v1.openshift-master-host[1]: apply errored, but we're indicating that via the Error pointer rather than returning it: could not inspect: could not inspect node, node is currently 'inspect failed', last error was 'timeout reached while inspecting the node'"
level=debug msg="2019/06/21 06:11:48 [ERROR] module.masters: eval: *terraform.EvalApplyPost, err: could not inspect: could not inspect node, node is currently 'inspect failed', last error was 'timeout reached while inspecting the node'"
level=debug msg="2019/06/21 06:11:48 [ERROR] module.masters: eval: *terraform.EvalSequence, err: could not inspect: could not inspect node, node is currently 'inspect failed', last error was 'timeout reached while inspecting the node'"
level=debug msg="2019/06/21 06:11:48 [DEBUG] module.masters.ironic_node_v1.openshift-master-host[0]: apply errored, but we're indicating that via the Error pointer rather than returning it: could not inspect: could not inspect node, node is currently 'inspect failed', last error was 'timeout reached while inspecting the node'"
level=debug msg="2019/06/21 06:11:48 [ERROR] module.masters: eval: *terraform.EvalApplyPost, err: could not inspect: could not inspect node, node is currently 'inspect failed', last error was 'timeout reached while inspecting the node'"
level=debug msg="2019/06/21 06:11:48 [ERROR] module.masters: eval: *terraform.EvalSequence, err: could not inspect: could not inspect node, node is currently 'inspect failed', last error was 'timeout reached while inspecting the node'"
level=error
level=error msg="Error: could not inspect: could not inspect node, node is currently 'inspect failed', last error was 'timeout reached while inspecting the node'"
level=error
level=error msg="  on ../../../tmp/kni-install-883347742/masters/main.tf line 9, in resource \"ironic_node_v1\" \"openshift-master-host\":"
level=error msg="   9: resource \"ironic_node_v1\" \"openshift-master-host\" {"
level=error
level=error
level=error
level=error msg="Error: could not inspect: could not inspect node, node is currently 'inspect failed', last error was 'timeout reached while inspecting the node'"
level=error
level=error msg="  on ../../../tmp/kni-install-883347742/masters/main.tf line 9, in resource \"ironic_node_v1\" \"openshift-master-host\":"
level=error msg="   9: resource \"ironic_node_v1\" \"openshift-master-host\" {"
level=error
level=error
level=error
level=error msg="Error: could not inspect: could not inspect node, node is currently 'inspect failed', last error was 'timeout reached while inspecting the node'"
level=error
level=error msg="  on ../../../tmp/kni-install-883347742/masters/main.tf line 9, in resource \"ironic_node_v1\" \"openshift-master-host\":"
level=error msg="   9: resource \"ironic_node_v1\" \"openshift-master-host\" {"
level=error
level=error
2019-06-21T06:11:48.646-0400 [DEBUG] plugin: plugin process exited: path=/home/metal/dev-scripts/ocp/openshift-install pid=170597
2019-06-21T06:11:48.646-0400 [DEBUG] plugin: plugin exited
2019-06-21T06:11:48.647-0400 [DEBUG] plugin: plugin process exited: path=/home/metal/dev-scripts/ocp/openshift-install pid=170707
2019-06-21T06:11:48.647-0400 [DEBUG] plugin: plugin exited
2019-06-21T06:11:48.647-0400 [DEBUG] plugin: plugin process exited: path=/home/metal/dev-scripts/ocp/openshift-install pid=170806
2019-06-21T06:11:48.647-0400 [DEBUG] plugin: plugin exited
level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"
[metal@server1 dev-scripts]$ 

Let me know anything specific id needed to debug the issue.

**Comment by bkunal** [comment]
Sees similar to https://github.com/openshift-metal3/dev-scripts/issues/569

**Comment by hardys** [comment]
> Seems similar to #569

Both failures happened running terraform but I don't think they are the same - your error is related to the introspection of the nodes, I'd start with running ```openstack baremetal node list``` then ```openstack baremetal node show <name or id>``` for any failing servers to see what the actual error is - all the error reported shows us is that something failed during introspection, see this readme for how:

https://github.com/openshift-metal3/dev-scripts/blob/master/README.md

The next steps to debug would be to look at the primary console for the nodes (was there some error booting the IPA inspection ramdisk?) and also look at the logs from the ironic-inspector container for any clues, there are a few reasons this can happen, and most of them are environment dependent (particularly in the baremetal case)

**Comment by bkunal** [comment]
I did make clean and re-executed scripts. This time cluster creation was at least successful. I will get back if anything is needed. But for now, this can be closed.
