### ISSUE TITLE
make[1]: *** No rule to make target `dep'.  Stop.

### ISSUE THREAD

**Issue by chunfuwen** [openshift-metal3/dev-scripts#665]
when install local environment using make, observe below error:
************************************************************
+ pushd /home/chwen/go/src/github.com/operator-framework/operator-sdk
~/go/src/github.com/operator-framework/operator-sdk ~/dev-scripts
+ git checkout master
Already on 'master'
+ make dep
make[1]: Entering directory `/home/chwen/go/src/github.com/operator-framework/operator-sdk'
make[1]: *** No rule to make target `dep'.  Stop.
make[1]: Leaving directory `/home/chwen/go/src/github.com/operator-framework/operator-sdk'
make: *** [repo_sync] Error 2
************************************************************

**Comment by stbenjam** [comment]
Fixed in #664
