### ISSUE TITLE
ipa-downloader on master exits with "Failed connect to 192.168.111.1:80; Connection timed out"

### ISSUE THREAD

**Issue by achuzhoy** [openshift-metal3/dev-scripts#678]
ipa-downloader on master exits with "Failed connect to 192.168.111.1:80; Connection timed out"

This issue occurs on a BM setup deployment. 
The IP 192.168.111.1 isn't reachable - we need to point a non-hardcoded IP.

**Comment by hardys** [comment]
Thanks, this is a known issue, but it's good to have a bug to track it.

Basically we need the BMO pod fully integrated via the MAO, and for the installer to generate a configmap such that we're including the correct IPs for various things, including the cacheurl which I think is the one causing this error (as a side note, it shouldn't be fatal, it'll just take longer to download the image from the internet).

As an interim solution we can probably sed this yaml (you can modify locally to confirm it resolves the issue):

https://github.com/openshift-metal3/dev-scripts/blob/master/ironic_bmo_configmap.yaml#L14

**Comment by achuzhoy** [comment]
Note that the provisioning interface on BM setup shouldn't be ens3.
Setting it to eno1 on mine.

**Comment by hardys** [comment]
This should be resolved via https://github.com/openshift-metal3/dev-scripts/pull/676

**Comment by hardys** [comment]
This will be resolved by #676 (merged) and https://github.com/openshift-metal3/dev-scripts/pull/692

**Comment by hardys** [comment]
closing this since the PRs above landed, this should be resolved by setting CLUSTER_PRO_IF appropriately in your environment
