### ISSUE TITLE
Rebooting the RHEL8 helper makes it unreachable

### ISSUE THREAD

**Issue by e-minguez** [openshift-metal3/dev-scripts#688]
**Describe the bug**
After configuring the ifcfg-* files and rebooting the helper, it is unreachable because the network service is not enabled in RHEL8

**To Reproduce**
Run the 02 script and reboot the helper node.

**Expected/observed behavior**
Cannot log-in via network and `ip a` shows no IPs

**Additional context**

**Comment by hardys** [comment]
The network service is enabled by default provided a network interface is enabled during the installation AFAIK?

I'm not sure this is actually specific to RHEL8, or just a side-effect of how it was installed?  Can you provide more details?

**Comment by e-minguez** [comment]
Network scripts are deprecated in RHEL8 and they are no longer provided by default (according to the docs) https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/configuring_and_managing_networking/index#Using-NetworkManager-with-sysconfig-files_getting-started-with-networking-devices-with-NetworkManager

Maybe it is just a matter of removing the `NM_CONTROLLED=no` setting?

**Comment by hardys** [comment]
> Maybe it is just a matter of removing the `NM_CONTROLLED=no` setting?

No the configuration files themselves are now a deprecated interface, thanks for the reminder :)

I think to replace them we'll need to switch to using `nmcli` in the scripts instead of creating the ifcfg files, which also aligns better with how things work on the (RHEL8 based) RHCOS image.
