### ISSUE TITLE
Drop custom image registry config manifest

### ISSUE THREAD

**Issue by russellb** [openshift-metal3/dev-scripts#704]
This issue is to track the removal of:

https://github.com/openshift-metal3/dev-scripts/blob/master/assets/templates/99_registry.yaml

It can be removed when the following PR is merged:

https://github.com/openshift/cluster-image-registry-operator/pull/332

**Comment by dhellmann** [comment]
@russellb  I see #623 refers to this. Does that resolve this issue, or is there still work to do?

**Comment by russellb** [comment]
There's still work to do.  99_registry.yaml is still there.  It's pending outcome of https://github.com/openshift/cluster-image-registry-operator/pull/332
