### ISSUE TITLE
Wrong ironic_endpoint and ironic_inspector_endpoint on baremetal

### ISSUE THREAD

**Issue by e-minguez** [openshift-metal3/dev-scripts#707]
**Describe the bug**
`ironic-bmo-configmap` has `ironic_endpoint: http://172.22.0.3:6385/v1/` and `ironic_inspector_endpoint: http://172.22.0.3:5050/v1/` but on baremetal deployments, I believe it should be the provisioning IP of the helper node instead.

**To Reproduce**
Run dev-scripts to completion and observe the `ironic-bmo-configmap`

**Expected/observed behavior**
The endpoints are calculated depending on the environment.

**Additional context**

**Comment by dhellmann** [comment]
We're moving ironic into the cluster, and it will run at the .3 address by default.

**Comment by russellb** [comment]
see discussion on #709 - if you're having a problem with ironic in the cluster, let's take a look
