### ISSUE TITLE
Need to move the creation of mariadb password to a different location

### ISSUE THREAD

**Issue by sadasu** [openshift-metal3/dev-scripts#723]
dev-scripts currently creates a Secret that contains the mariadb password here:
https://github.com/openshift-metal3/dev-scripts/blob/master/08_deploy_bmo.sh#L44

Creation of this Secret should either move to the installer or to the MAO.

**Comment by hardys** [comment]
The 08 script was removed, now handled via https://github.com/openshift-metal3/dev-scripts/blob/master/mariadb-password.yaml

@sadasu please can you link the MAO or installer issues raised to track the resolution of this?  Thanks!

**Comment by hardys** [comment]
https://github.com/openshift-metal3/dev-scripts/pull/799

https://github.com/openshift/machine-api-operator/pull/389

**Comment by hardys** [comment]
Closed via #799 and openshift/machine-api-operator#389
