### ISSUE TITLE
Machine/Node linkage required for machine healthcheck

### ISSUE THREAD

**Issue by markmc** [openshift-metal3/dev-scripts#725]
The [machine healthcheck controller](https://github.com/openshift/machine-api-operator/tree/master/pkg/controller/machinehealthcheck) requires Machines to have nodeRef linkage back to the corresponding Node.

The [nodelink controller](https://github.com/openshift/machine-api-operator/pull/321) establishes this linkage, but it requires the IP address to be set on the Machine object in order to do so. 

OpenShift does not currently automatically do this for masters with the baremetal IPI platform. We have been tracking this issue because it [prevents master server CSRs being automatically approved](https://github.com/openshift-metal3/dev-scripts/issues/260#issuecomment-516431191).

I'm filing this issue to track the requirement that the nodeRef linkage is required for machine healthcheck, and not just for auto-approving CSRs.

In openshift-metal3/dev-scripts#714 we are proposing re-adding a temporary workaround to manually create this linkage as a post-install step.

**Comment by e-minguez** [comment]
Just in case, even if the scripts are executed, the IPs are not added to the machine object https://github.com/openshift-metal3/dev-scripts/pull/714#issuecomment-517648471

**Comment by dhellmann** [comment]
This should be addressed by #730

**Comment by hardys** [comment]
https://github.com/openshift-metal3/dev-scripts/pull/730 landed, anything else needed to close this issue?

**Comment by russellb** [comment]
#730 is more of a workaround.  As long as the workaround is still needed, I'd consider this an open bug we need to track.

**Comment by hardys** [comment]
> #730 is more of a workaround. As long as the workaround is still needed, I'd consider this an open bug we need to track.

Ack, I was thinking the long-term solution was already tracked via https://github.com/openshift-metal3/dev-scripts/issues/260

**Comment by dhellmann** [comment]
I'm going to close this in favor of tracking the work in #260.
