### ISSUE TITLE
Checks in common.sh should run in 01_install_requirements.sh

### ISSUE THREAD

**Issue by markmc** [openshift-metal3/dev-scripts#727]
In openshift-metal3/dev-scripts#186

> You could also add these checks to common.sh. That way they run no matter which script you're running.

and then openshift-metal3/dev-scripts#279

> It doesn't appear 01 needs anything from common.sh to run other than logging

i.e. things like checking the OS version, password-less sudo, etc. no longer happens when you run 01_install_requirements.sh

Maybe we should move these checks into a `checks.sh` or something?

**Comment by russellb** [comment]
common.sh is sourced in 01_install_requirements.sh now, so I think we can close this
