### ISSUE TITLE
Generated install-config fails validation with latest installer

### ISSUE THREAD

**Issue by hardys** [openshift-metal3/dev-scripts#735]
**Describe the bug**
Since https://github.com/openshift/installer/pull/2140 landed there are additional checks on the VIP IPs, which fail in our default dev-scripts setup like:

level=fatal msg="failed to fetch Master Machines: failed to load asset \"Install Config\": invalid \"install-config.yaml\" file: [platform.baremetal.apiVIP: Invalid value: \"192.168.111.5\": the virtual IP is expected to be in 10.0.0.0/16 subnet, platform.baremetal.ingressVIP: Invalid value: \"192.168.111.4\": the virtual IP is expected to be in 10.0.0.0/16 subnet, platform.baremetal.dnsVIP: Invalid value: \"192.168.111.2\": the virtual IP is expected to be in 10.0.0.0/16 subnet]"
make: *** [ocp_run] Error 1

Maybe @bcrochet has some patch already from when this was tested, but I guess we need to set the subnet to overlap with the VIP IPs in `ocp_install_env.sh`

**Comment by stbenjam** [comment]
Do you have this change?

https://github.com/openshift-metal3/dev-scripts/blob/master/ocp_install_env.sh#L66

**Comment by stbenjam** [comment]
(If you have my bump branch checked out, it's not in there, needs rebasing)

**Comment by hardys** [comment]
Ah yes that's it, thanks @stbenjam :+1:
