### ISSUE TITLE
Ironic nodes registered to the bmo Ironic are lost after rebooting the master node where bmo pod is running

### ISSUE THREAD

**Issue by mcornea** [openshift-metal3/dev-scripts#738]
Description of problem:

Ironic nodes registered to the bmo Ironic are lost after rebooting the master node where bmo pod is running.

Steps to Reproduce:

[cloud-user@rhhi-node-worker-0 dev-scripts]$ export OS_URL=http://172.22.0.3:6385
[cloud-user@rhhi-node-worker-0 dev-scripts]$ export OS_TOKEN=fake-token
[cloud-user@rhhi-node-worker-0 dev-scripts]$ openstack baremetal node list
+--------------------------------------+--------------------+---------------+-------------+--------------------+-------------+
| UUID                                 | Name               | Instance UUID | Power State | Provisioning State | Maintenance |
+--------------------------------------+--------------------+---------------+-------------+--------------------+-------------+
| 56904f3a-88da-4ea9-b237-155216d12d9d | openshift-master-0 | None          | power on    | adopt failed       | False       |
| 21466e2a-a0c5-4a0e-ae4b-788e02c4fa0c | openshift-master-1 | None          | power on    | adopt failed       | False       |
| 1b48b778-d341-4e21-ad9e-a49ae9619ed1 | openshift-master-2 | None          | power on    | adopt failed       | False       |
+--------------------------------------+--------------------+---------------+-------------+--------------------+-------------+

[cloud-user@rhhi-node-worker-0 dev-scripts]$ oc -n openshift-machine-api get pods/metal3-baremetal-operator-7469cd5f89-5h2fs -o yaml | grep master-
  nodeName: rhhi-node-master-1

Power off the master node where the baremetal-operator pod is running:
openstack baremetal node power off openshift-master-1 #ran on provisionhost ironic

Wait for the node to go offline:
[cloud-user@rhhi-node-worker-0 ~]$ oc get nodes
NAME                 STATUS     ROLES           AGE   VERSION
rhhi-node-master-0   Ready      master,worker   82m   v1.14.0+739670a83
rhhi-node-master-1   NotReady   master,worker   82m   v1.14.0+739670a83
rhhi-node-master-2   Ready      master,worker   82m   v1.14.0+739670a83

Power on the node back on:
openstack baremetal node power on openshift-master-1 #ran on provisionhost ironic

Wait for the node to go online:
[cloud-user@rhhi-node-worker-0 ~]$ oc get nodes
NAME                 STATUS   ROLES           AGE   VERSION
rhhi-node-master-0   Ready    master,worker   84m   v1.14.0+739670a83
rhhi-node-master-1   Ready    master,worker   84m   v1.14.0+739670a83
rhhi-node-master-2   Ready    master,worker   84m   v1.14.0+739670a83

Check baremetal nodes list:

[cloud-user@rhhi-node-worker-0 ~]$ export OS_URL=http://172.22.0.3:6385
[cloud-user@rhhi-node-worker-0 ~]$ export OS_TOKEN=fake-token
[cloud-user@rhhi-node-worker-0 ~]$ openstack baremetal node list

Version-Release number of selected component (if applicable):

How reproducible:
100%

Actual results:
Ironic nodes which were registered during initial deployment are lost after rebooting the master node where the bmo pod is running.

Expected results:
The ironic nodes details persist across reboots.

**Comment by dhellmann** [comment]
This is a known design limitation of the current implementation and is not related to dev-scripts. We're working on some changes to fix this, starting with https://github.com/metal3-io/baremetal-operator/pull/278

**Comment by rlopez133** [comment]
@mcornea - instead of export OS_URL=http://172.22.0.3:6385 , do export OS_URL=http://localhost:6385/ , and see if now openstack baremetal node list gives you the result your looking for.

**Comment by mcornea** [comment]
> @mcornea - instead of export OS_URL=http://172.22.0.3:6385 , do export OS_URL=http://localhost:6385/ , and see if now openstack baremetal node list gives you the result your looking for.

Yeah, the ironic instance running on the provisioning host does return the hosts but given that the provisioning host is only used temporary during I'd expect that the nodes become manageable by the   bmo Ironic instance once the deployment has finished.

**Comment by hardys** [comment]
Yeah this is probably best tracked against the BMO repo, since dev-scripts is working as expected here.

Also note that when https://github.com/openshift-metal3/dev-scripts/pull/726 lands we'll no longer run ironic at all on the provisioning host, only on the ephemeral bootstrap VM (and then the cluster).

**Comment by dhellmann** [comment]
I think https://github.com/metal3-io/baremetal-operator/pull/278 should have fixed this. Are you still seeing this problem?

**Comment by mcornea** [comment]
> I think [metal3-io/baremetal-operator#278](https://github.com/metal3-io/baremetal-operator/pull/278) should have fixed this. Are you still seeing this problem?

I couldn't reproduce the issue so it looks like it's fixed. I'll close the issue, thanks!
