### ISSUE TITLE
MAO managed Metal3 deployment not functional

### ISSUE THREAD

**Issue by russellb** [openshift-metal3/dev-scripts#739]
The machine-api-operator now manages the Deployment of the baremetal-operator and its dependencies.  The Deployment is named `metal3`.  This support first merged in https://github.com/openshift-metal3/dev-scripts/pull/726

This Deployment does not currently come up successfully.  This issue is used to track the work to get it in a functional state.

---

Relevant PRs or Issues:

- [x] https://github.com/openshift/machine-api-operator/pull/373
- [x] https://github.com/openshift/machine-api-operator/pull/374
- [x] https://github.com/openshift/machine-api-operator/pull/377
- [x] https://github.com/openshift/machine-api-operator/pull/378
- [x] https://github.com/openshift/machine-api-operator/pull/380
- [x] https://github.com/openshift/machine-api-operator/pull/381
- [x] https://github.com/openshift/ironic-inspector-image/pull/13
- [x] ~~https://github.com/openshift/machine-api-operator/pull/382~~
- [x] https://github.com/openshift-metal3/dev-scripts/pull/752
- [x] Fix `run_ci.sh` to wait for a successful worker again - https://github.com/openshift-metal3/dev-scripts/pull/783
- [x] https://github.com/metal3-io/ironic-image/pull/88
- [x] https://github.com/metal3-io/ironic-image/pull/89
- [x] https://github.com/openshift/ironic-image/pull/15 (cherry-pick of above two PRs)
- [x] https://github.com/metal3-io/ironic-inspector-image/pull/33
- [x] https://github.com/openshift/ironic-inspector-image/pull/14
- [x] https://github.com/openshift/machine-api-operator/pull/384
- [x] https://github.com/openshift/machine-api-operator/pull/385
- [x] https://github.com/openshift/machine-api-operator/pull/385
- [x] https://github.com/openshift/machine-api-operator/pull/386
- [x] https://github.com/openshift-metal3/dev-scripts/issues/761
- [x] revert of https://github.com/openshift/ironic-inspector-image/pull/13 - https://github.com/openshift/ironic-inspector-image/pull/17 -- fixes introspection in nightly builds

Fixing version of ironic included in CI releases:
- [ ] openshift/release#4835
- [ ] openshift/release#4836
- [ ] openshift/release#4837

**Comment by hardys** [comment]
I propose we close this and track fixing the version of ironic in CI builds separately, since it's not strictly related to the issues we had with the MAO

**Comment by hardys** [comment]
https://github.com/openshift-metal3/dev-scripts/issues/788 raised to track CI image issues
