### ISSUE TITLE
link-machine-and-node.sh was stuck in dead waiting since timeout is not given

### ISSUE THREAD

**Issue by chunfuwen** [openshift-metal3/dev-scripts#742]
In my local deployment, link-machine-and-node.sh was stuck in dead waiting 
*********************************************************************************************
<pre>+ echo -n &apos;Waiting for openshift-master-0 to stabilize ... &apos;
Waiting for openshift-master-0 to stabilize ... + time_diff=-1566200031
+ [[ -1566200031 -gt &apos;&apos; ]]
++ curl -s -X GET http://localhost:8001/apis/metal3.io/v1alpha1/namespaces/openshift-machine-api/baremetalhosts/openshift-master-0/status -H &apos;Accept: application/json&apos; -H &apos;Content-Type: application/json&apos; -H &apos;User-Agent: linck-machine-and-node&apos;
++ jq .status.provisioning.state
++ sed &apos;s/&quot;//g&apos;
+ state=null
+ echo null
null
+ &apos;[&apos; null = &apos;externally provisioned&apos; &apos;]&apos;
+ sleep 5
+ true
+ echo -n &apos;Waiting for openshift-master-0 to stabilize ... &apos;
Waiting for openshift-master-0 to stabilize ... + time_diff=-1566200031
+ [[ -1566200031 -gt &apos;&apos; ]]
++ curl -s -X GET http://localhost:8001/apis/metal3.io/v1alpha1/namespaces/openshift-machine-api/baremetalhosts/openshift-master-0/status -H &apos;Accept: application/json&apos; -H &apos;Content-Type: application/json&apos; -H &apos;User-Agent: linck-machine-and-node&apos;
++ jq .status.provisioning.state
++ sed &apos;s/&quot;//g&apos;
+ state=null
+ echo null
null
+ &apos;[&apos; null = &apos;externally provisioned&apos; &apos;]&apos;
+ sleep 5
+ true
+ echo -n &apos;Waiting for openshift-master-0 to stabilize ... &apos;
Waiting for openshift-master-0 to stabilize ... + time_diff=-1566200031
+ [[ -1566200031 -gt &apos;&apos; ]]
++ jq .status.provisioning.state
++ curl -s -X GET http://localhost:8001/apis/metal3.io/v1alpha1/namespaces/openshift-machine-api/baremetalhosts/openshift-master-0/status -H &apos;Accept: application/json&apos; -H &apos;Content-Type: application/json&apos; -H &apos;User-Agent: linck-machine-and-node&apos;
++ sed &apos;s/&quot;//g&apos;
+ state=null
+ echo null
</pre>

**Comment by hardys** [comment]
I suspect this is a combination of https://github.com/openshift-metal3/dev-scripts/issues/739 and https://github.com/openshift-metal3/dev-scripts/issues/736 ?

**Comment by dhellmann** [comment]
> I suspect this is a combination of #739 and #736 ?

That seems likely

**Comment by pliurh** [comment]
I've experienced the same situation.

**Comment by e-minguez** [comment]
I've managed to workaround it by modifying the link-machine-and-node.sh script as:

```
$ git diff
diff --git a/link-machine-and-node.sh b/link-machine-and-node.sh
index 29fb82c..01d618b 100755
--- a/link-machine-and-node.sh
+++ b/link-machine-and-node.sh
@@ -49,6 +49,16 @@ ipaddr=$(echo "${addresses}" | jq '.[] | select(. | .type == "InternalIP") | .ad
 host_patch='
 {
   "status": {
+    "poweredOn": true,
+    "operationalStatus": "",
+    "hardwareProfile": "",
+    "provisioning": {
+      "state": "",
+      "ID": ""
+    },
+    "goodCredentials": {},
+    "triedCredentials":  {},
+    "errorMessage": "",
     "hardware": {
       "hostname": "'${hostname}'",
       "nics": [
@@ -98,16 +108,14 @@ while true; do
         return 1
     fi
 
-    state=$(curl -s \
+    externally_provisioned=$(curl -s \
                  -X GET \
                  ${HOST_PROXY_API_PATH}/${host}/status \
                  -H "Accept: application/json" \
                  -H "Content-Type: application/json" \
                  -H "User-Agent: link-machine-and-node" \
-                | jq '.status.provisioning.state' \
-                | sed 's/"//g')
-    echo "$state"
-    if [ "$state" = "externally provisioned" ]; then
+                | jq '.spec.externallyProvisioned' )
+    if [ "$externally_provisioned" ]; then
         break
     fi
     sleep 5
```

**Comment by dhellmann** [comment]
@e-minguez the part of your workaround that is "working" is looking at .spec.externallyProvisioned, which is the flag telling the operator that the host should be treated as externally provisioned but is not an accurate representation of the internal state of the host and whether it is actually "ready" yet. So you're basically turning the check into a no-op and skipping the wait.

**Comment by e-minguez** [comment]
> @e-minguez the part of your workaround that is "working" is looking at .spec.externallyProvisioned, which is the flag telling the operator that the host should be treated as externally provisioned but is not an accurate representation of the internal state of the host and whether it is actually "ready" yet. So you're basically turning the check into a no-op and skipping the wait.

Yes, it was just a quick fix to make it work as @honza was asking me for a cluster to debug the pod number mismatching in the baremetalhost dashboard.

**Comment by dhellmann** [comment]
@chunfuwen and @e-minguez are either of you still seeing this issue?

**Comment by e-minguez** [comment]
I've successfully deployed a couple of environments and it worked flawlessly. Thanks!
