### ISSUE TITLE
 haproxy exits after some time after many restarts. 

### ISSUE THREAD

**Issue by achuzhoy** [openshift-metal3/dev-scripts#746]
A deployment succeeds and I'm able to work with the deployed OCP setup.

Coming to a setup after a weekend, I'm no longer able to run any oc command, get:

$ oc get node
The connection to the server api.qe3.kni.lab.eng.bos.redhat.com:6443 was refused - did you specify the right host or port?

Checking the masters, I see that the haproxy has "exited" status and 1077 restarts:
[core@openshift-master-1 ~]$ sudo crictl ps -a|grep haproxy
4d32597d22be1       99df6b1b3e6eda8b479846e1e03b768f9bdc94f97f8b338fd771ebdb050476cb                                                                  2 minutes ago       Exited              haproxy                                  1077                ca54e3db58ede
6c7b42da28c26       c232e0e4cadb2d962a5e05774e0aa8e83b68597f21c27745d6c36a5bc4742ef4                                                                  2 days ago          Running             haproxy-monitor                          1                   ca54e3db58ede
86439b34570d4       c232e0e4cadb2d962a5e05774e0aa8e83b68597f21c27745d6c36a5bc4742ef4                                                                  2 days ago          Exited              haproxy-monitor                          0                   6f3409ae4107c

[core@openshift-master-1 ~]$ sudo crictl logs 4d32597d22be1
+ declare -r haproxy_sock=/var/run/haproxy/haproxy-master.sock
+ declare -r haproxy_log_sock=/var/run/haproxy/haproxy-log.sock
+ export -f msg_handler
+ export -f reload_haproxy
+ '[' -S /var/run/haproxy/haproxy-master.sock ']'
+ socat UNIX-LISTEN:/var/run/haproxy/haproxy-master.sock,fork 'system:bash -c msg_handler'
+ socat UNIX-RECV:/var/run/haproxy/haproxy-log.sock STDOUT
2019/08/19 13:36:41 socat[8] E "/var/run/haproxy/haproxy-log.sock" exists
[core@openshift-master-1 ~]$

[core@openshift-master-0 ~]$ sudo crictl ps -a|grep haproxy
81723c5b36428       99df6b1b3e6eda8b479846e1e03b768f9bdc94f97f8b338fd771ebdb050476cb                                                                  About a minute ago   Exited              haproxy                                   2661                45061ae8cbf6b
aa3648e1a3fec       c232e0e4cadb2d962a5e05774e0aa8e83b68597f21c27745d6c36a5bc4742ef4                                                                  2 days ago           Running             haproxy-monitor                           1                   45061ae8cbf6b
a6909fdb85bfc       c232e0e4cadb2d962a5e05774e0aa8e83b68597f21c27745d6c36a5bc4742ef4                                                                  2 days ago           Exited              haproxy-monitor                           0                   21b9bbcb005d9
[core@openshift-master-0 ~]$ sudo crictl logs 81723c5b36428
+ declare -r haproxy_sock=/var/run/haproxy/haproxy-master.sock
+ declare -r haproxy_log_sock=/var/run/haproxy/haproxy-log.sock
+ export -f msg_handler
+ export -f reload_haproxy
+ '[' -S /var/run/haproxy/haproxy-master.sock ']'
+ socat UNIX-LISTEN:/var/run/haproxy/haproxy-master.sock,fork 'system:bash -c msg_handler'
+ socat UNIX-RECV:/var/run/haproxy/haproxy-log.sock STDOUT
2019/08/19 13:41:58 socat[8] E "/var/run/haproxy/haproxy-log.sock" exists

[core@openshift-master-2 ~]$ sudo crictl ps -a|grep haproxy
db7e8896a1ab9       c232e0e4cadb2d962a5e05774e0aa8e83b68597f21c27745d6c36a5bc4742ef4                                                                  15 seconds ago       Exited              haproxy-monitor                         3                   7b9686cc02aa5
ab3f259496707       99df6b1b3e6eda8b479846e1e03b768f9bdc94f97f8b338fd771ebdb050476cb                                                                  About a minute ago   Exited              haproxy                                 1141                7b9686cc02aa5
[core@openshift-master-2 ~]$ sudo crictl logs ab3f259496707
+ declare -r haproxy_sock=/var/run/haproxy/haproxy-master.sock
+ declare -r haproxy_log_sock=/var/run/haproxy/haproxy-log.sock
+ export -f msg_handler
+ export -f reload_haproxy
+ '[' -S /var/run/haproxy/haproxy-master.sock ']'
+ socat UNIX-LISTEN:/var/run/haproxy/haproxy-master.sock,fork 'system:bash -c msg_handler'
+ socat UNIX-RECV:/var/run/haproxy/haproxy-log.sock STDOUT
2019/08/19 13:42:47 socat[8] E "/var/run/haproxy/haproxy-log.sock" exists
[core@openshift-master-2 ~]$

**Comment by hardys** [comment]
cc @yboaron

**Comment by yboaron** [comment]
@hardys , @achuzhoy 

I assume that u hit the bug that was resolved by [1] fix in MCO,
to double-check that, could u please share the content of /etc/kubernetes/manifest/haproxy.yaml from one of the masters?

[1] https://github.com/openshift/machine-config-operator/commit/c3616cd0822093249823c4c3701219b49b8beced

**Comment by dhellmann** [comment]
Is this still an issue?

**Comment by yboaron** [comment]
@dhellmann , this issue already resolved.
