### ISSUE TITLE
rhcos image download causing timeouts on bootstrap node

### ISSUE THREAD

**Issue by derekhiggins** [openshift-metal3/dev-scripts#748]
**Describe the bug**
startironic.sh uses the default gateway in order to find cached images (on the bootstrap virt host)
`CACHEURL="http://$(ip r | grep default | head -n1 | awk '{print $3}')/images"`

This logic doesn't work a baremetal env where the default gateway isn't the bootstrap host machine

```
+ '[' -n http://10.19.130.254/images ']'
+ curl --fail -O http://10.19.130.254/images/rhcos-ootpa-latest.qcow2.headers
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to 10.19.130.254:80; Connection refused

```
the downloader containers then go onto download from https://releases-art-rhcos.svc.ci.openshift.org

which can take well in excess of 25 minutes causing the installer to timeout

**Comment by rdoxenham** [comment]
https://github.com/openshift/installer/issues/2232

**Comment by rdoxenham** [comment]
https://github.com/openshift/installer/pull/2233

**Comment by hardys** [comment]
Yeah I think this should be fixed by the PR above (thanks @rdoxenham) - the logic in startironic.sh was flawed, because we need to look at the default route for the provisioning interface, not the external network default route (where there is no CACHEURL httpd running)

**Comment by stbenjam** [comment]
Let’s track this in the installer repo unless we need to fix something in dev-scripts.
