### ISSUE TITLE
Baremetal hardware details 'hardcoded'

### ISSUE THREAD

**Issue by e-minguez** [openshift-metal3/dev-scripts#767]
**Describe the bug**
When running dev-scripts in a baremetal environment, the dashboard shows:

```
Bios
    Version: 1.11.0-2.el7
    Vendor: SeaBIOS
    Date: 04/01/2014
Hardware
    4x Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz CPU
    0 B RAM
    0 B Disk
```

**To Reproduce**
Run `make` in a baremetal environment

**Expected/observed behavior**
Show the proper data.

**Additional context**
https://github.com/openshift-metal3/dev-scripts/blob/master/link-machine-and-node.sh#L50-L88

I believe this is because the hosts are not inspected and the inspection is planned for later releases but just in case.

Thanks.

**Comment by hardys** [comment]
Is this for master or worker nodes?

In the case of masters I think this is expected, until we get the IPA in-band inspection feature that allows us to retrospectively populate the data on the BMH objects.

For workers, since https://github.com/openshift/ironic-image/pull/15 then introspection should run, therefore the data will be populated

**Comment by e-minguez** [comment]
> Is this for master or worker nodes?
> 

Masters

> In the case of masters I think this is expected, until we get the IPA in-band inspection feature that allows us to retrospectively populate the data on the BMH objects.
> 

Understood. Shall I close the issue or leave it open to track that progress? Thanks!

**Comment by hardys** [comment]
> Understood. Shall I close the issue or leave it open to track that progress? Thanks!

We already have https://github.com/metal3-io/baremetal-operator/issues/242 so lets close this and track the status there.
