### ISSUE TITLE
 Cluster operator machine-config is reporting a failure: Failed to resync 4.2.0-0.nightly-2019-08-30-102614 because: timed out waiting for the condition during syncRequiredMachineConfigPools 

### ISSUE THREAD

**Issue by achuzhoy** [openshift-metal3/dev-scripts#786]
Environment:
4.2.0-0.nightly-2019-08-30-102614:

Deploying RHHI.next fails with:

level=fatal msg="failed to initialize the cluster: Cluster operator machine-config is reporting a failure: Failed to resync 4.2.0-0.nightly-2019-08-30-102614 because: timed out waiting for the condition during syncRequiredMachineConfigPools: pool master has not progressed to latest configuration: configuration status for pool master is empty: pool is degraded because nodes fail with \"3 nodes are reporting degraded status on sync\": \"Node openshift-master-2.qe3.kni.lab.eng.bos.redhat.com is reporting: \\\"failed to run pivot: failed to start machine-config-daemon-host.service: exit status 1\\\", Node openshift-master-0.qe3.kni.lab.eng.bos.redhat.com is reporting: \\\"failed to run pivot: failed to start machine-config-daemon-host.service: exit status 1\\\", Node openshift-master-1.qe3.kni.lab.eng.bos.redhat.com is reporting: \\\"machineconfig.machineconfiguration.openshift.io \\\\\\\"rendered-master-ea0e9728f7d997f5d87e4b96e10cf1b1\\\\\\\" not found\\\"\", retrying"

$ oc get clusterversion version -o json
{
    "apiVersion": "config.openshift.io/v1",
    "kind": "ClusterVersion",
    "metadata": {
        "creationTimestamp": "2019-08-30T18:01:10Z",
        "generation": 1,
        "name": "version",
        "resourceVersion": "19648",
        "selfLink": "/apis/config.openshift.io/v1/clusterversions/version",
        "uid": "25e219a3-cb50-11e9-b004-525400c6f653"
    },
    "spec": {
        "channel": "stable-4.2",
        "clusterID": "91f841d8-b7d0-4fab-b0a8-02f18f86fc72",
        "upstream": "https://api.openshift.com/api/upgrades_info/v1/graph"
    },
    "status": {
        "availableUpdates": null,
        "conditions": [
            {
                "lastTransitionTime": "2019-08-30T18:01:31Z",
                "status": "False",
                "type": "Available"
            },
            {
                "lastTransitionTime": "2019-08-30T18:29:21Z",
                "message": "Cluster operator machine-config is reporting a failure: Failed to resync 4.2.0-0.nightly-2019-08-30-102614 because: timed out waiting for the condition during syncRequiredMachineConfigPools: pool master has not progressed to latest configuration: configuration status for pool master is empty: pool is degraded because nodes fail with \"3 nodes are reporting degraded status on sync\": \"Node openshift-master-2.qe3.kni.lab.eng.bos.redhat.com is reporting: \\\"failed to run pivot: failed to start machine-config-daemon-host.service: exit status 1\\\", Node openshift-master-0.qe3.kni.lab.eng.bos.redhat.com is reporting: \\\"failed to run pivot: failed to start machine-config-daemon-host.service: exit status 1\\\", Node openshift-master-1.qe3.kni.lab.eng.bos.redhat.com is reporting: \\\"machineconfig.machineconfiguration.openshift.io \\\\\\\"rendered-master-ea0e9728f7d997f5d87e4b96e10cf1b1\\\\\\\" not found\\\"\", retrying",
                "reason": "ClusterOperatorDegraded",
                "status": "True",
                "type": "Failing"
            },
            {
                "lastTransitionTime": "2019-08-30T18:01:31Z",
                "message": "Unable to apply 4.2.0-0.nightly-2019-08-30-102614: the cluster operator machine-config is degraded",
                "reason": "ClusterOperatorDegraded",
                "status": "True",
                "type": "Progressing"
            },
            {
                "lastTransitionTime": "2019-08-30T18:01:31Z",
                "message": "Unable to retrieve available updates: currently installed version 4.2.0-0.nightly-2019-08-30-102614 not found in the \"stable-4.2\" channel",
                "reason": "RemoteFailed",
                "status": "False",
                "type": "RetrievedUpdates"
            }
        ],
        "desired": {
            "force": false,
            "image": "registry.svc.ci.openshift.org/ocp/release@sha256:2af4802bf2eea2e3d2113ee155fb0a49c7f2435cb80bc8b3f22722c975f3f3e5",
            "version": "4.2.0-0.nightly-2019-08-30-102614"
        },
        "history": [
            {
                "completionTime": null,
                "image": "registry.svc.ci.openshift.org/ocp/release@sha256:2af4802bf2eea2e3d2113ee155fb0a49c7f2435cb80bc8b3f22722c975f3f3e5",
                "startedTime": "2019-08-30T18:01:31Z",
                "state": "Partial",
                "verified": false,
                "version": "4.2.0-0.nightly-2019-08-30-102614"
            }
        ],
        "observedGeneration": 1,
        "versionHash": "CP-2QhB7v60="
    }
}

**Comment by stbenjam** [comment]
We've been seeing some reports of this, CI was also seeing the same failure. Nightly is now pointing at 4.2.0-0.nightly-2019-08-30-142130, and I got a successful install locally, would you mind trying again?

**Comment by achuzhoy** [comment]
Sure. Thanks!

**Comment by stbenjam** [comment]
Looks like we have a bunch of reports of successful dev-scripts installs after 2019-08-30-142130, please re-open if you run into issues. 

The install-scripts issue (https://github.com/openshift-kni/install-scripts/issues/55) is still valid, but related to missing manifests in that repo.
