### ISSUE TITLE
Failed to deploy a cluster due to unavailability of trunk.rdoproject.org

### ISSUE THREAD

**Issue by gklein** [openshift-metal3/dev-scripts#787]
**Describe the bug**
Failed to deploy a cluster due to unavailability of trunk.rdoproject.org
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='trunk.rdoproject.org', port=443): Max retries exceeded with url: /centos7/current-tripleo/delorean.repo (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5e26776490>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**To Reproduce**
run make to install a cluster

**Expected/observed behavior**
```
Package yum-plugin-priorities-1.1.31-50.el7.noarch already installed and latest version
Nothing to do
Traceback (most recent call last):
  File "/bin/tripleo-repos", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/tripleo_repos/main.py", line 349, in main
    _install_repos(args, base_path)
  File "/usr/lib/python2.7/site-packages/tripleo_repos/main.py", line 296, in _install_repos
    args)
  File "/usr/lib/python2.7/site-packages/tripleo_repos/main.py", line 143, in _get_repo
    r = requests.get(path)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='trunk.rdoproject.org', port=443): Max retries exceeded with url: /centos7/current-tripleo/delorean.repo (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5e26776490>: Failed to establish a new connection: [Errno 110] Connection timed out',))
make: *** [requirements] Error 1
```

**Comment by chunfuwen** [comment]
If you deploy on existing old machine, you can work around this by remove lines code between 6 and 159 in  01_install_requirements.sh, which is related to rpm packages installation. The reason why it work is that  all required packages are actually on your machine 
Therefore, after that just run make clean all, it could create one cluster for you

**Comment by hardys** [comment]
Was this just a temporary outage?  Not sure there's anything to fix in dev-scripts if so, we pull from various web locations, and if any of them go down, stuff will break.

I did notice some bad domain SSL cert warnings connecting manually to trunk.rdoproject today, could that be related?

**Comment by hardys** [comment]
https://lists.rdoproject.org/pipermail/dev/2019-September/009134.html
