### ISSUE TITLE
Testing with CI builds is not possible, wrong Ironic version

### ISSUE THREAD

**Issue by hardys** [openshift-metal3/dev-scripts#788]
Testing with upstream CI (vs nightly ART) builds is currently not possible due to repo issues that result in the wrong (old) version of Ironic getting installed in the images.

Resolution of this is being tracked via the following issues, but until this is fixed testing with arbitrary CI builds will not be possible.

- [x] openshift/release#4835
- [x] ~~openshift/release#4836~~
- [x] ~~openshift/release#4837~~
- [x] openshift/release#5241
- [x] openshift/release#5240

**Comment by elfosardo** [comment]
FYI the updated content in the CI will be for 4.3 only

**Comment by elfosardo** [comment]
this should be fixed now! \o/
