### ISSUE TITLE
python-requests install may be needed to wrap into 01_install_requirements.sh for  Centos  platform

### ISSUE THREAD

**Issue by chunfuwen** [openshift-metal3/dev-scripts#805]
I ran 01_install_requirements.sh on CentOS Linux release 7.6.1810 (Core) with python 2 as default python. 
And it throw error that requests package is missed.

**Comment by hardys** [comment]
Please provide more details - we need to see the logs from 01_install_requirements.sh (in dev-scripts/logs) so that we can see what requires this and why it's failing, it should be installed here:

https://github.com/metal3-io/metal3-dev-env/blob/master/vm-setup/vars/packages_installation.yml#L54

As a general note, please always include more details when raising a bug report - it's a waste of all our time to raise bugs like this without enough detail/context to attempt debugging and providing a fix, thanks!

**Comment by chunfuwen** [comment]
this is newly installed centos machine, and I executed install step one step , not use make under dev-scripts, and this happen when execute 01_install_requirements.sh


<pre>+ &apos;[&apos; &apos;!&apos; -d tripleo-repos &apos;]&apos;
+ git clone https://git.openstack.org/openstack/tripleo-repos
Cloning into &apos;tripleo-repos&apos;...
+ pushd tripleo-repos
~/tripleo-repos ~
+ sudo python setup.py install
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution <span style="background-color:#FCE94F">opt</span>ion: &apos;long_description_content_type&apos;
  warnings.warn(msg)
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution <span style="background-color:#FCE94F">opt</span>ion: &apos;project_urls&apos;
  warnings.warn(msg)

Installed /home/chwen/tripleo-repos/pbr-5.4.3-py2.7.egg
[pbr] Generating ChangeLog
running install
[pbr] Writing ChangeLog
[pbr] Generating ChangeLog
[pbr] ChangeLog complete (0.0s)
[pbr] Generating AUTHORS
[pbr] AUTHORS complete (0.0s)
running build
running build_py
creating build
creating build/lib
creating build/lib/tripleo_repos
creating build/lib/tripleo_repos/tests
copying tripleo_repos/tests/__init__.py -&gt; build/lib/tripleo_repos/tests
copying tripleo_repos/tests/test_main.py -&gt; build/lib/tripleo_repos/tests
copying tripleo_repos/__init__.py -&gt; build/lib/tripleo_repos
copying tripleo_repos/main.py -&gt; build/lib/tripleo_repos
running egg_info
creating tripleo_repos.egg-info
writing pbr to tripleo_repos.egg-info/pbr.json
writing requirements to tripleo_repos.egg-info/requires.txt
writing tripleo_repos.egg-info/PKG-INFO
writing top-level names to tripleo_repos.egg-info/top_level.txt
writing dependency_links to tripleo_repos.egg-info/dependency_links.txt
writing entry points to tripleo_repos.egg-info/entry_points.txt
[pbr] Processing SOURCES.txt
writing manifest file &apos;tripleo_repos.egg-info/SOURCES.txt&apos;
[pbr] In git context, generating filelist from git
warning: no previously-included files matching &apos;*.pyc&apos; found anywhere in distribution
writing manifest file &apos;tripleo_repos.egg-info/SOURCES.txt&apos;
running install_lib
creating /usr/lib/python2.7/site-packages/tripleo_repos
creating /usr/lib/python2.7/site-packages/tripleo_repos/tests
copying build/lib/tripleo_repos/tests/__init__.py -&gt; /usr/lib/python2.7/site-packages/tripleo_repos/tests
copying build/lib/tripleo_repos/tests/test_main.py -&gt; /usr/lib/python2.7/site-packages/tripleo_repos/tests
copying build/lib/tripleo_repos/__init__.py -&gt; /usr/lib/python2.7/site-packages/tripleo_repos
copying build/lib/tripleo_repos/main.py -&gt; /usr/lib/python2.7/site-packages/tripleo_repos
byte-compiling /usr/lib/python2.7/site-packages/tripleo_repos/tests/__init__.py to __init__.pyc
byte-compiling /usr/lib/python2.7/site-packages/tripleo_repos/tests/test_main.py to test_main.pyc
byte-compiling /usr/lib/python2.7/site-packages/tripleo_repos/__init__.py to __init__.pyc
byte-compiling /usr/lib/python2.7/site-packages/tripleo_repos/main.py to main.pyc
running install_egg_info
Copying tripleo_repos.egg-info to /usr/lib/python2.7/site-packages/tripleo_repos-0.0.1.dev88-py2.7.egg-info
running install_scripts
Installing tripleo-repos script to /usr/bin
+ popd
~
+ sudo tripleo-repos current-tripleo
Traceback (most recent call last):
  File &quot;/bin/tripleo-repos&quot;, line 6, in &lt;module&gt;
    from tripleo_repos.main import main
  File &quot;/usr/lib/python2.7/site-packages/tripleo_repos/main.py&quot;, line 24, in &lt;module&gt;
    import requests
ImportError: No module named requests
                                        </pre>

**Comment by hardys** [comment]
This should be fixed via https://github.com/openshift-metal3/dev-scripts/pull/804
