### ISSUE TITLE
[RHEL8] python3 has not been configured as an alternative for python

### ISSUE THREAD

**Issue by knowncitizen** [openshift-metal3/dev-scripts#811]
**Describe the bug**
Getting a failure running make on dev-scripts on fresh RHEL8.

**To Reproduce**
Did a fresh install of RHEL8 and a DNF update.
Subscribed via subscription-manager
DNF install make, git, cloned the dev-scripts repo. `2eac2ea7dd61a02678c573e1c6ec4b7537a7e1a3`
Ran `make`.
Failed here:
```+ sudo subscription-manager repos --enable=ansible-2-for-rhel-8-x86_64-rpms
Repository 'ansible-2-for-rhel-8-x86_64-rpms' is enabled for this system.
+ sudo alternatives --set python /usr/bin/python3
/usr/bin/python3 has not been configured as an alternative for python
make: *** [Makefile:9: requirements] Error 2```

No overrides. Virtual.

**Expected/observed behavior**
Expected to get past this issue.

**Additional context**
N/A

**Comment by hardys** [comment]
Are you installing on a minmal environment where no python3 is actually installed?

**Comment by hardys** [comment]
Ok confirmed, this is due to #804 - it only happens when using a minimal RHEL8 install such that /usr/bin/python3 does not exist, the fix is to ensure it is installed before the call to alternatives, I'll push a PR and transfer this issue to metal3-dev-env

**Comment by knowncitizen** [comment]
Just getting started this morning, I didn't try going around it last night. It was minimal and I didn't ensure Python3 was installed.  This should fix it.
