### ISSUE TITLE
Metal3 CI can't test against other installer branches

### ISSUE THREAD

**Issue by stbenjam** [openshift-metal3/dev-scripts#822]
**Describe the bug**

When testing an openshift/installer PR to a branch other than master (e.g. release-4.2), CI fails to apply the PR diff.

**To Reproduce**

Open a pull request against openshift/installer, in a branch other than `master`

**Expected/observed behavior**

Expect PR to be applied to the correct branch

Actual results is it tries to apply always to `master`

```
+ cd installer
+ git pull --no-edit https://github.com/stbenjam/installer fix-rhcos
From https://github.com/stbenjam/installer
 * branch            fix-rhcos  -> FETCH_HEAD
Auto-merging upi/vsphere/main.tf
CONFLICT (content): Merge conflict in upi/vsphere/main.tf
Auto-merging upi/vsphere/machine/variables.tf
CONFLICT (content): Merge conflict in upi/vsphere/machine/variables.tf
Auto-merging upi/vsphere/machine/main.tf
CONFLICT (content): Merge conflict in upi/vsphere/machine/main.tf
Auto-merging data/data/rhcos.json
CONFLICT (content): Merge conflict in data/data/rhcos.json
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by stbenjam** [comment]
@derekhiggins It looks like this happens before run_ci.sh, is this something we could fix in Jenkins? Although, this was an edge case and it may not matter if we're moving to Prow soon-ish anyway.

**Comment by derekhiggins** [comment]
@stbenjam ya, there is an assumption in the code (in jenkins and also in the code that triggers the jobs), it should be easy enough to support. Are their any examples of PR's with the problem at the moment? The one I found is closed and the pr branch is gone, If not I'll just create one.

**Comment by stbenjam** [comment]
@derekhiggins Awesome thanks, that’s the only PR I know about. I think we’ve only needed to do this once ever so far.
