### ISSUE TITLE
01_install_requirements.sh / Always running registry for disconnected install

### ISSUE THREAD

**Issue by mazzystr** [openshift-metal3/dev-scripts#864]
**Describe the bug**
01_install_requirements.sh always runs tasks such as ssl cert creation and starting Docker registry.

These tasks should be conditional based on a boolean (boolean in shell scripts, LOL!) set in config.sh. 

**To Reproduce**
./01_install_requirements.sh

**Expected/observed behavior**
I want to run a normal install and pull images from quay.io.  All the cert create and Docker registry tasks are extraneous.

**Additional context**

**Comment by hardys** [comment]
Yeah we could make them optional, but we'd need to be careful to either leave them enabled by default, or re-enable automatically when someone specifies `*_LOCAL_IMAGE` which relies on the local registry.

The reason it's enabled by default is that the majority of developers using these scripts are regularly testing from-source container builds, so it was easier to just enable it always.

**Comment by hardys** [comment]
Oh I see now this is referring to https://github.com/openshift-metal3/dev-scripts/pull/856 which is not yet merged, I'll close this and we can discuss on the PR, if it merges without the requested fix we can reopen this.
