### ISSUE TITLE
ironic_hosts.json.example and related code is redundant

### ISSUE THREAD

**Issue by mazzystr** [openshift-metal3/dev-scripts#874]
**Describe the bug**
Users are already expected to correctly populate install-config.yaml with neessary keyvalues to run the installer making ironic_hosts.json.example and related code redundant

 ironic_hosts.json.example and all related code should be removed.  

**To Reproduce**
Follow normal installation procedure for bare-metal

**Expected/observed behavior**

**Additional context**

**Comment by hardys** [comment]
We can possibly replace this with a way to override the install-config contents, but right now this is not redundant - in dev-scripts we generate the install-config, it's not populated manually by the user.

In the case where folks want to deploy baremetal they historically have overridden the NODES_FILE by copying and editing the `ironic_hosts.json.example`

One option is to say dev-scripts no longer supports any baremetal testing (and that openshift-kni/baremetal-deploy should be used instead), but that may be unacceptable to some folks doing development work on baremetal features.

**Comment by hardys** [comment]
Ok going to close this as stale, for now NODES_FILE is supported, and for folks testing on baremetal the example may still be useful.
