### ISSUE TITLE
Building the installer locally doesn't work with MIRROR_IMAGES

### ISSUE THREAD

**Issue by cybertron** [openshift-metal3/dev-scripts#880]
**Describe the bug**
When MIRROR_IMAGES is in use and KNI_INSTALL_FROM_GIT=true is set, the installer ends up referencing a release that it can't access. This is because https://github.com/openshift-metal3/dev-scripts/blob/1536fdeaeac964ecc27e876ec3e509e09563b93d/common.sh#L82 explicitly sets the release image to the upstream release, but with mirroring we remove the upstream pull secret and only provide the one for the local registry.

**To Reproduce**
Set MIRROR_IMAGES=true and KNI_INSTALL_FROM_GIT=true before running dev-scripts. Do not include any LOCAL_IMAGE overrides as that further changes the behavior.

**Expected/observed behavior**
I expect the custom installer to use the local registry with the mirrored images. What is actually happening is that the installer tries to pull an upstream release image that it doesn't have credentials for.

**Comment by cybertron** [comment]
#881 unblocked me because with that fix and a LOCAL_IMAGE override my deployment succeeds. However, I think that may be masking the problem. With LOCAL_IMAGE set it's ignoring the local mirror and deploying from the ci registry anyway. Possibly the LOCAL_IMAGE logic is overwriting the mirrored release that gets created? Something is still definitely wrong though.

**Comment by hardys** [comment]
@cybertron thanks for the report, I can confirm this is broken, with both MIRROR_IMAGES and a LOCAL_IMAGE set I'm seeing the bootstrap VM use the upstream registry if I also set KNI_INSTALL_FROM_GIT.
