### ISSUE TITLE
Undefined variable errors in common.sh

### ISSUE THREAD

**Issue by cybertron** [openshift-metal3/dev-scripts#885]
**Describe the bug**
My dev-scripts runs with master are now failing on a few undefined variable errors. I assume this is a result of https://github.com/openshift-metal3/dev-scripts/commit/316574977739e441f0d817a622c3916236667b34

I'm playing whack-a-mole with the undefined variables and will hopefully be able to push a fix shortly.

**Comment by zaneb** [comment]
May be the same issue as #884?

**Comment by cybertron** [comment]
Oh, looks like it. The fix must have merged between when I pulled and when I opened this.

**Comment by zaneb** [comment]
I just merged it after I commented here, since I saw that Doug had updated it after my earlier comment :)
