### ISSUE TITLE
yq no longer installed via metal3-dev-env

### ISSUE THREAD

**Issue by kot-begemot-uk** [openshift-metal3/dev-scripts#888]
Installer fails when executing PIP to build more-itertools required by yq.

Python more-itertools are now at version 8.1 which is python 3 only.

The last version usable in a 2.x environment is 5.0.

if 5.0 is already installed on the host manually (by pulling the relevant release from github and building it locally), the installer succeeds.

**Comment by hardys** [comment]
What OS are you using?  I assume CentOS7?

**Comment by kot-begemot-uk** [comment]
Up to date Centos 7 starting from a fresh install.

**Comment by hardys** [comment]
Thanks @kot-begemot-uk sounds like we need to pin to a version that works for Centos 7 and also yq installation got removed in https://github.com/metal3-io/metal3-dev-env/pull/178 so we'll need to do that only in dev-scripts (or remove/rework the code which requires yq potentially)

**Comment by russellb** [comment]
it looks like this was centos 7 specific, which we need to drop anyway.  I pushed a PR (#1000) to officially mark CentOS 7 as deprecated.

**Comment by hardys** [comment]
> it looks like this was centos 7 specific, which we need to drop anyway. I pushed a PR (#1000) to officially mark CentOS 7 as deprecated.

I'm not sure it is CentOS7 specific - I don't think yq is packaged for CentOS8 either?

It's only an issue if we hit this line:

https://github.com/openshift-metal3/dev-scripts/blob/master/utils.sh#L11

Probably the easiest fix will be to modify assets/yaml_patch.py to read the `.spec.config.storage.files[].path` but we only use it for the optional chronyd templates, so perhaps there's some other way we could template those instead

**Comment by russellb** [comment]
Sorry about that @hardys ... I interpreted the comments here incorrectly and didn't look at how yq was used.  It was still a good reminder to deprecate CentOS 7, but I've reopened this bug.
