### ISSUE TITLE
can we have make master and make worker

### ISSUE THREAD

**Issue by kot-begemot-uk** [openshift-metal3/dev-scripts#889]
Can we have make master and make worker as targets?

**Comment by russellb** [comment]
have any more info about how you would want those to behave?

PRs welcome, of course :-)

**Comment by hardys** [comment]
Can you expand a bit on the use-case here please?  

The fact that workers are deployed after the openshift-install run is a bug, and when the installer supports creating the metal3 config ref https://github.com/openshift/installer/pull/2449/ we'll most likely want to just set the NUM_WORKERS in the install-config replicas here:

https://github.com/openshift-metal3/dev-scripts/blob/master/ocp_install_env.sh#L74

So while it would be trivial now to add such makefile targets, we know they will break in the near future, so I'm hesitant to do so

**Comment by kot-begemot-uk** [comment]
I was thinking along the lines of the other issue I filed about VM persistence. My idea was to separate the build of the VMs and actual spin up of the VMs so you can:

1) Build them and reuse them
2) Spin them up in different networking scenarios in order to play with networking - OVN and Multus.

My ultimate goal here is to have setup which allows me to play with the networking side and specifically with OVN and (maybe) multus. At present it just builds them "as is" and there is a very small amount of moving parts I can play with on the networking side.

**Comment by hardys** [comment]
> I was thinking along the lines of the other issue I filed about VM persistence. My idea was to separate the build of the VMs and actual spin up of the VMs so you can:
> 
>     1. Build them and reuse them

This should already be possible by doing e.g `make ocp_cleanup ocp_run register_hosts` or you can run the related scripts manually of course

>     2. Spin them up in different networking scenarios in order to play with networking - OVN and Multus.
> 
> My ultimate goal here is to have setup which allows me to play with the networking side and specifically with OVN and (maybe) multus. At present it just builds them "as is" and there is a very small amount of moving parts I can play with on the networking side.

Ok it sounds like we may need some additional variables to enable the configurations you want to test, PRs are certainly welcome to enable that, my concern really was more around permanently decoupling the master/worker deployment, and AFAICT that's not really the primary issue here?

**Comment by hardys** [comment]
There is also the exisxting `make redeploy` target which cleans up everything except the VMs, does that suit your requirements?

**Comment by russellb** [comment]
looks like this has gone a bit stale, feel free to reopen this if appropriate ...
