### ISSUE TITLE
VM images are marked as non-persistent

### ISSUE THREAD

**Issue by kot-begemot-uk** [openshift-metal3/dev-scripts#890]
VM images at present are marked as non-persistent. 

The corresponding stanza in the libvirt xml is <on_poweroff>destroy</on_poweroff>

Unless I am mistaken, this means that there is no way to shut down and restart a setup and it has to be rebuilt from scratch every time.

**Comment by hardys** [comment]
This is a known issue, it's one of several things which likely don't survive a reboot.

For developer testing (which is the primary purpose of these scripts) that is OK but if someone wants to do the work to make things persist over reboot such a PR would be welcome.

**Comment by kot-begemot-uk** [comment]
OK. I will look at it. Can't promise though :)

**Comment by stbenjam** [comment]
We'd accept a patch to make this configurable, but at the moment we don't plan to fix this. 
Developer deployments tend to be ephemeral. 

/close
