### ISSUE TITLE
Restore support for 4.3 to master

### ISSUE THREAD

**Issue by stbenjam** [openshift-metal3/dev-scripts#907]
Support for 4.3 was removed from master as part of https://github.com/openshift-metal3/dev-scripts/pull/897.

`master` should have 4.3 support restored, but still keeping the minimal configmap (and eventual removal) for 4.4.

Until then, the release-4.3 branch can be used to deploy 4.3.

https://github.com/openshift-metal3/dev-scripts/tree/release-4.3

**Comment by hardys** [comment]
Closed via https://github.com/openshift-metal3/dev-scripts/pull/920
